#!/usr/bin/env bash
# FMEA rail pins — from the 2026-06-10/11 per-phase edge-case audit
# (spec: 2026-06-10-fmea-and-future-roadmap.md).
set -u
here="$(cd "$(dirname "$0")" && pwd)"
cd "$here/../.." || exit 2
P="plugins/mega-sdd"
rc=0
fail() { echo "FAIL: $1"; rc=1; }
pass() { echo "PASS: $1"; }

# U1 — extract-intelligence secret-scan gate
grep -q 'secret-scan.sh" --redact' "$P/skills/extract-intelligence/SKILL.md" \
  && pass "U1: extract-intelligence secret-scan gate" || fail "U1: KB secret-scan gate missing"

# U2 / U3 retired in 9.0 P1: the symlink/big-file rail and the monorepo
# primary-app rail were Step-4 / Step-2 rails of the scan-codebase walk, and
# scan-codebase (the classic scan-first spine) is deleted
# (docs/superpowers/specs/2026-09-27-v9-simplification-design.md §3).

# U4 — binding REGENERATED banner. 9.0 P1: the bind-codebase binding-md
# template is gone (§7 #10 — not relocated); the banner's single source is the
# PHASE-0 stamp in derive-binding-json.sh (kept for layout-2 read support; §7 #8
# — its marker string never changes while layout-2 is readable). Pin the BANNER
# literal (leading `"> `), not the idempotency check that also names the marker.
grep -qF '"> REGENERATED by bind-codebase on every run' "$P/scripts/derive-binding-json.sh" \
  && pass "U4: binding.md do-not-hand-edit banner" || fail "U4: binding banner missing"

# D1 retired in 9.0 P3b: the run is inline (one context, plan order), so no two
# units write concurrently; --parallel and its Overlap rail are retired flags.

# D2 — PENDING-SYNC lifecycle
grep -q 'PENDING-SYNC.archive.md' "$P/skills/orchestrate-flow/references/sync-digest.md" \
  && pass "D2: PENDING-SYNC lifecycle (archive + pressure + stale marker)" || fail "D2: lifecycle missing"

# D3 retired in 9.0 P1: the failure mode was two concurrent whole-vault binds
# (bind-codebase Step 6) interleaving binding.md. bind-codebase is deleted; the
# JIT bind writes one bolts/U-*/binding.json per unit via write-unit-binding.sh
# and never touches vault.json, so the relocated vault-core.md §Concurrency
# contract rightly drops the bind-codebase writer row that carried the pin.

# D4 — unit-count scale advisory (9.0 P1: the generate-units unit walk moved to
# plan/references/unit-procedure.md, loaded by plan Step 4)
grep -q 'Scale advisory' "$P/skills/plan/references/unit-procedure.md" \
  && pass "D4: unit-count scale advisory" || fail "D4: scale advisory missing"

# D5 — test-framework preflight
grep -q 'Test framework present' "$P/skills/execute-bolts/SKILL.md" \
  && grep -q 'TDD without a runner is fiction' "$P/skills/execute-bolts/SKILL.md" \
  && pass "D5: test-runner preflight (dep_missing, never fabricate green)" || fail "D5: runner preflight missing"

# D6 — commit hook rejection halt
grep -q 'commit_rejected_by_hook' "$P/skills/execute-bolts/SKILL.md" \
  && grep -q 'commit_rejected_by_hook' "$P/skills/execute-bolts/references/halts-and-handoff.md" \
  && pass "D6: commit_rejected_by_hook halt registered" || fail "D6: hook-rejection halt missing"

# D8 — sync git-state guard
grep -q 'rebase-merge' "$P/commands/sync.md" \
  && pass "D8: sync mid-rebase guard" || fail "D8: rebase guard missing"

# E2 — headless/CI section
grep -q '## Headless / CI' "$P/references/project-config.md" \
  && grep -q -- '--bare' "$P/references/project-config.md" \
  && pass "E2: headless/CI guidance (incl. --bare hook bypass)" || fail "E2: CI section missing"

# E3 — multi-dev note
grep -q 'Multi-dev note' "$P/references/paths.md" \
  && pass "E3: multi-dev vault.json guidance" || fail "E3: multi-dev note missing"

# E1 — FUNCTIONAL: python3-absent fail-closed gate (3 states)
T=$(mktemp -d)
mkdir -p "$T/bin" "$T/proj/.mega-sdd"
for t in cat sed grep head printf dirname pwd bash sh uname date; do
  [ -x "/bin/$t" ] && ln -s "/bin/$t" "$T/bin/$t" 2>/dev/null
  [ -x "/usr/bin/$t" ] && ln -sf "/usr/bin/$t" "$T/bin/$t" 2>/dev/null
done
printf '{"status": "FAIL"}' > "$T/proj/.mega-sdd/.validation-blockers.json"
O1=$(printf '{"tool_name":"Skill","cwd":"%s","tool_input":{"skill":"mega-sdd:execute-bolts"}}' "$T/proj" | env PATH="$T/bin" bash "$P/hooks/pre-tool-use" 2>/dev/null)
printf '{"status": "PASS"}' > "$T/proj/.mega-sdd/.validation-blockers.json"
O2=$(printf '{"tool_name":"Skill","cwd":"%s","tool_input":{"skill":"mega-sdd:execute-bolts"}}' "$T/proj" | env PATH="$T/bin" bash "$P/hooks/pre-tool-use" 2>/dev/null)
O3=$(printf '{"tool_name":"Bash","cwd":"%s","tool_input":{"command":"ls"}}' "$T/proj" | env PATH="$T/bin" bash "$P/hooks/pre-tool-use" 2>/dev/null)
case "$O1" in *'"permissionDecision": "deny"'*) pass "E1a: no-python3 + FAIL blockers → BLOCKED (fail-closed)";; *) fail "E1a: expected block, got: ${O1:0:60}";; esac
[ -z "$O2" ] && pass "E1b: no-python3 + PASS blockers → allowed" || fail "E1b: expected allow, got: ${O2:0:60}"
[ -z "$O3" ] && pass "E1c: no-python3 + non-gated tool → allowed" || fail "E1c: expected allow, got: ${O3:0:60}"
rm -rf "$T"

[ $rc -eq 0 ] && echo "ALL PASS" || echo "FAILURES PRESENT"
exit $rc
