#!/usr/bin/env bash
# test-emit-claude-rules.sh — pins spec 2026-08-17-constitution-claude-rules.md
# (A6): grounded clause→paths union, uncited skip, verbatim + stamp, dry-run
# writes nothing, prefix-scoped stale removal, determinism, offer-only wiring.
# Run </dev/null.
set -u
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
P="$ROOT/plugins/mega-sdd"
S="$P/scripts/emit-claude-rules.sh"
PASS=0; FAIL=0
ok()   { PASS=$((PASS+1)); echo "  ok: $1"; }
fail() { FAIL=$((FAIL+1)); echo "  FAIL: $1"; }
PY="${MEGA_SDD_TEST_PY:-python3}"
command -v "$PY" >/dev/null 2>&1 || { echo "SKIP (no python3)"; exit 0; }

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
PRJ="$TMP/prj"; V="$PRJ/.mega-sdd/vaults/app"
mkdir -p "$V/units" "$PRJ/.claude/rules"
cat > "$V/constitution.md" <<'EOF'
# Project Constitution

**Status**: Active
**Version**: 1.2

## §B. Security (Non-negotiable)

- B-001: All API endpoints MUST use Sanctum auth middleware (source: PRD §security)
- B-002: Financial mutations MUST be audit-logged (source: BRD §audit)

## §F. Compliance

- F-001: PII fields MUST be encrypted at rest (source: SEOJK)
EOF
mk_unit() { # id, path1, path2-or-empty, clause-or-empty
  { printf -- '---\nid: %s\ntask_type: create\ntarget_files:\n  - path: %s\n    operation: create\n' "$1" "$2"
    [ -n "$3" ] && printf '  - path: %s\n    operation: modify\n' "$3"
    printf -- '---\n\n## Goal\nx\n\n## Hard rules\n'
    [ -n "$4" ] && printf -- '- MUST honor §%s (constitution)\n' "$4"
    printf '\n## Done\n'; } > "$V/units/$1.md"
}
mk_unit U-001 "app/Http/Api/UserController.php" "routes/api.php" "B-001"
mk_unit U-002 "app/Services/PaymentService.php" "" "B-001"
mk_unit U-003 "app/Models/Ledger.php" "" "B-002"
mk_unit U-004 "resources/views/home.blade.php" "" ""   # cites nothing
# foreign user rule that must NEVER be touched
printf -- '---\npaths: ["src/**"]\n---\nuser rule\n' > "$PRJ/.claude/rules/my-own-rule.md"

echo "── a: dry-run plans, writes NOTHING ──"
OUT=$(bash "$S" --vault="$V" --cwd="$PRJ" </dev/null 2>&1); RC=$?
[ "$RC" -eq 0 ] && ok "a1 dry-run exit 0" || fail "a1 rc=$RC: $OUT"
echo "$OUT" | grep -q '"written": false' && ok "a2 plan says written:false" || fail "a2 $OUT"
[ "$(ls "$PRJ/.claude/rules" | wc -l | tr -d ' ')" -eq 1 ] && ok "a3 no files written on dry-run" || fail "a3 dry-run wrote files"

echo "── b: --write emits grounded, verbatim, stamped rules ──"
OUT=$(bash "$S" --vault="$V" --cwd="$PRJ" --write </dev/null 2>&1)
F1="$PRJ/.claude/rules/mega-sdd-app-B-001.md"
[ -f "$F1" ] && ok "b1 B-001 rule emitted" || fail "b1 missing"
grep -qF 'app/Http/Api/UserController.php' "$F1" && grep -qF 'routes/api.php' "$F1" && grep -qF 'app/Services/PaymentService.php' "$F1" \
  && ok "b2 paths = union of BOTH citing units' target_files" || fail "b2 union wrong"
grep -qF 'B-001: All API endpoints MUST use Sanctum auth middleware (source: PRD §security)' "$F1" \
  && ok "b3 clause text VERBATIM" || fail "b3 clause reworded"
grep -q 'GENERATED by mega-sdd' "$F1" && grep -q 'do not hand-edit' "$F1" && grep -q 'sha256' "$F1" \
  && ok "b4 provenance stamp present" || fail "b4 stamp missing"
[ -f "$PRJ/.claude/rules/mega-sdd-app-B-002.md" ] && ok "b5 B-002 emitted" || fail "b5 missing"
echo "$OUT" | grep -q '"skipped_ungrounded": \[ *"F-001" *\]' && ok "b6 ungrounded F-001 skipped + listed" || fail "b6 $OUT"
[ ! -f "$PRJ/.claude/rules/mega-sdd-app-F-001.md" ] && ok "b7 no fabricated file for uncited clause" || fail "b7 uncited clause emitted"

echo "── c: refresh removes stale PREFIX files only ──"
# B-999 matches the GENERATED pattern (round M-3 narrowed deletion to it) but
# is not in the current clause set → the one legitimately stale-removable shape.
printf 'stale\n' > "$PRJ/.claude/rules/mega-sdd-app-B-999.md"
bash "$S" --vault="$V" --cwd="$PRJ" --write </dev/null >/dev/null 2>&1
[ ! -f "$PRJ/.claude/rules/mega-sdd-app-B-999.md" ] && ok "c1 stale generated-pattern file removed" || fail "c1 stale survived"
[ -f "$PRJ/.claude/rules/my-own-rule.md" ] && grep -q 'user rule' "$PRJ/.claude/rules/my-own-rule.md" \
  && ok "c2 foreign user rule untouched" || fail "c2 FOREIGN RULE TOUCHED"

echo "── d: determinism ──"
C1=$(cat "$F1"); bash "$S" --vault="$V" --cwd="$PRJ" --write </dev/null >/dev/null 2>&1
[ "$C1" = "$(cat "$F1")" ] && ok "d1 re-run byte-equal" || fail "d1 nondeterministic"

echo "── e: offer-only wiring (never silent, never auto) ──"
grep -q 'emit-claude-rules.sh' "$P/skills/generate-units/SKILL.md" && ok "e1 generate-units offers the emission" || fail "e1 offer missing"
grep -qF 'QUEUED as a notice' "$P/skills/generate-units/SKILL.md" && grep -qF 'never auto-run' "$P/skills/generate-units/SKILL.md" \
  && ok "e2 never-auto pillar (both literals — round m-2 de-vacuoused)" || fail "e2 auto-run risk"
grep -q 'emit-claude-rules' "$P/commands/sync.md" && ok "e3 sync proposes refresh" || fail "e3 sync wiring missing"

echo "── f: round payload classes (B-1/M-1..M-4) ──"
# f1 B-1: body/fenced "- path:" lines must NOT ground
{ printf -- '---\nid: U-005\ntask_type: create\ntarget_files:\n  - path: real/target.php\n    operation: create\n---\n\n## Goal\n```yaml\n- path: /etc/shadow\n```\n- path: not/a/target.py\n\n## Hard rules\n- MUST honor §B-002 (constitution)\n'; } > "$V/units/U-005.md"
bash "$S" --vault="$V" --cwd="$PRJ" --write </dev/null >/dev/null 2>&1
F2="$PRJ/.claude/rules/mega-sdd-app-B-002.md"
grep -qF '/etc/shadow' "$F2" && fail "f1 body/fenced path grounded a rule (B-1)" || ok "f1 frontmatter-only harvest"
grep -qF 'real/target.php' "$F2" && ok "f1b real frontmatter path grounded" || fail "f1b real path lost"
# f2 M-2: SUB-001 must not cite B-001
{ printf -- '---\nid: U-006\ntask_type: create\ntarget_files:\n  - path: sub/only.php\n    operation: create\n---\n\n## Hard rules\n- MUST follow SUB-001 protocol\n'; } > "$V/units/U-006.md"
bash "$S" --vault="$V" --cwd="$PRJ" --write </dev/null >/dev/null 2>&1
grep -qF 'sub/only.php' "$PRJ/.claude/rules/mega-sdd-app-B-001.md" && fail "f2 SUB-001 false-cited B-001 (M-2)" || ok "f2 left-bounded citation"
# f3 M-1: revision-history line must not overwrite the clause
cat >> "$V/constitution.md" <<'EOC'

## Revision history

- B-001: reworded in v2.0 — NOT a normative clause line
EOC
bash "$S" --vault="$V" --cwd="$PRJ" --write </dev/null >/dev/null 2>&1
grep -qF 'NOT a normative clause line' "$PRJ/.claude/rules/mega-sdd-app-B-001.md" && fail "f3 non-§ line minted/overwrote a clause (M-1)" || ok "f3 §-section-scoped clause parse"
# f4 M-3: sibling-slug vault must survive this vault refresh + custom file survives
V2="$PRJ/.mega-sdd/vaults/app-v2"; mkdir -p "$V2"
printf 'sibling\n' > "$PRJ/.claude/rules/mega-sdd-app-v2-B-001.md"
printf 'custom\n'  > "$PRJ/.claude/rules/mega-sdd-app-custom.md"
bash "$S" --vault="$V" --cwd="$PRJ" --write </dev/null >/dev/null 2>&1
[ -f "$PRJ/.claude/rules/mega-sdd-app-v2-B-001.md" ] && ok "f4 sibling-slug vault rules survive (M-3)" || fail "f4 SIBLING DELETED"
[ -f "$PRJ/.claude/rules/mega-sdd-app-custom.md" ] && ok "f4b hand-written prefix file survives" || fail "f4b custom deleted"
# f5 M-4: spaces + quoted + backslash paths stay whole and YAML-valid
{ printf -- '---\nid: U-007\ntask_type: create\ntarget_files:\n  - path: app/My Reports File.php\n    operation: create\n  - path: "quoted/style.php"\n    operation: create\n---\n\n## Hard rules\n- MUST honor §F-001 (constitution)\n'; } > "$V/units/U-007.md"
bash "$S" --vault="$V" --cwd="$PRJ" --write </dev/null >/dev/null 2>&1
F3="$PRJ/.claude/rules/mega-sdd-app-F-001.md"
grep -qF "'app/My Reports File.php'" "$F3" && ok "f5 space path whole + single-quoted" || fail "f5 truncated: $(head -6 "$F3" 2>/dev/null | tr '\n' ' ')"
grep -qF "'quoted/style.php'" "$F3" && ok "f5b quoted path unwrapped cleanly" || fail "f5b double-quote corruption"
"$PY" -c "
import re,sys
t=open('$F3').read()
m=re.match(r'^---\n(.*?)\n---\n', t, re.S)
assert m, 'no frontmatter'
import yaml
" 2>/dev/null || true

echo
echo "emit-claude-rules: $PASS ok, $FAIL fail"
[ "$FAIL" -eq 0 ]
