# plugins/mega-sdd/scripts/_lib/distill-ui-ux.py
"""Sync-time distiller: ui-ux-pro-max CSVs -> mega-sdd design-intelligence references.

Runs ONLY at sync/release time (standalone since v7.4.0 — the sync-vendored.sh
wrapper was removed). mega-sdd runtime never
calls this — it reads the committed markdown/YAML output instead. No third-party deps
beyond PyYAML (already used by other mega-sdd sync tooling); falls back to a minimal
hand-rolled YAML emitter so the distiller never hard-depends on PyYAML at sync time.
"""
import argparse, csv, os, sys, re

def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.strip().lower()).strip("-")

def read_csv(path):
    if not os.path.isfile(path):
        return []
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

def emit_yaml_products(rows_products, rows_colors, out):
    # index colors.csv by Product Type for palette join
    color_by_pt = {r.get("Product Type", "").strip(): r for r in rows_colors}
    lines = ["# GENERATED by scripts/_lib/distill-ui-ux.py — do not hand-edit; re-run sync-ui-ux.sh.",
             "# Source: ui-ux-pro-max products.csv + colors.csv (MIT, nextlevelbuilder).",
             "products:"]
    count = 0
    for r in rows_products:
        pt = r.get("Product Type", "").strip()
        if not pt:
            continue
        c = color_by_pt.get(pt, {})
        palette = ", ".join(v for v in [
            f"primary {c.get('Primary','').strip()}" if c.get("Primary") else "",
            f"accent {c.get('Accent','').strip()}" if c.get("Accent") else "",
        ] if v) or (r.get("Color Palette Focus", "").strip())
        lines += [
            f"  {slug(pt)}:",
            f"    label: {yq(pt)}",
            f"    style: {yq(r.get('Primary Style Recommendation','').strip())}",
            f"    secondary_styles: {yq(r.get('Secondary Styles','').strip())}",
            f"    palette: {yq(palette)}",
            f"    typography: {yq('see typography-pairings.md — match by product mood/keywords')}",
            f"    a11y_baseline: {yq('WCAG AA')}",
            f"    considerations: {yq(r.get('Key Considerations','').strip())}",
        ]
        count += 1
    with open(os.path.join(out, "product-style-map.yaml"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return count

def yq(s):
    s = (s or "").replace('"', "'")
    return f'"{s}"'

def emit_md_table(out, fname, title, source, header, rows, cols):
    lines = [f"# {title}", "", f"> GENERATED by distill-ui-ux.py from {source} (MIT, nextlevelbuilder). Do not hand-edit.", "",
             "| " + " | ".join(header) + " |", "|" + "|".join(["---"] * len(header)) + "|"]
    for r in rows:
        cells = [(r.get(c, "") or "").replace("\n", " ").replace("|", "/").strip() for c in cols]
        if not cells[0]:
            continue
        lines.append("| " + " | ".join(cells) + " |")
    with open(os.path.join(out, fname), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", required=True, help="ui-ux-pro-max src/.../data dir")
    ap.add_argument("--out", required=True, help="output references/design-intelligence dir")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    products = read_csv(os.path.join(a.data, "products.csv"))
    colors = read_csv(os.path.join(a.data, "colors.csv"))
    styles = read_csv(os.path.join(a.data, "styles.csv"))
    typo = read_csv(os.path.join(a.data, "typography.csv"))
    ux = read_csv(os.path.join(a.data, "ux-guidelines.csv"))
    n = emit_yaml_products(products, colors, a.out)
    emit_md_table(a.out, "style-principles.md", "Style Principles", "styles.csv",
                  ["Style", "Best For", "Avoid For", "CSS Keywords"], styles,
                  ["Style Category", "Best For", "Do Not Use For", "CSS/Technical Keywords"])
    # (palette-principles.md emit removed v7.4.0 — zero runtime consumers; the
    # colors.csv palette JOIN above still feeds product-style-map.yaml.)
    emit_md_table(a.out, "typography-pairings.md", "Typography Pairings", "typography.csv",
                  ["Pairing", "Heading", "Body", "Mood", "Best For", "CSS Import"], typo,
                  ["Font Pairing Name", "Heading Font", "Body Font", "Mood/Style Keywords", "Best For", "CSS Import"])
    emit_md_table(a.out, "ux-rules.md", "UX Rules & Accessibility", "ux-guidelines.csv",
                  ["Category", "Issue", "Do", "Don't", "Severity"], ux,
                  ["Category", "Issue", "Do", "Don't", "Severity"])
    print(f"distilled: {n} products + styles/palette/typography/ux into {a.out}", file=sys.stderr)

if __name__ == "__main__":
    main()
