#!/usr/bin/env bash
# test-p2d-agent-contracts.sh — batch2 P2d (spec 2026-07-19-batch2-derive-and-diet.md):
# the four constant dispatch blocks (halt vocabulary, self-report template, rollback
# schema, provenance trailer shape) move from the per-dispatch prompt template into
# agents/bolt-implementer.md (the system-prompt M-09 precedent) — single source,
# marker strings byte-identical, per-dispatch prompt carries pointer + values.
#
#   1  agent carries the moved blocks whole (all 5 halt types, self-report keys,
#      step_type enum, trailer marker, whitelist_violation) — canonical vocab only
#   2-3 (dispatch template + context-enrichment pins) retired in P3 C5 with the builder;
#      the whole file goes with bolt-implementer in C6b
#   4  validate-bolt-artifacts.sh key strings unchanged (marker + bolt_self_report:)
#
# Run: bash tests/boilerplate-diet/test-p2d-agent-contracts.sh
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
P="${ROOT}/plugins/mega-sdd"
AG="$P/agents/bolt-implementer.md"
VBA="$P/scripts/validate-bolt-artifacts.sh"

FAILED=0
ok()   { printf '  \342\234\223 %s\n' "$*"; }
fail() { printf '  \342\234\227 FAIL: %s\n' "$*"; FAILED=1; }

echo "== P2d: dispatch constants are agent-carried, single source =="

# ── 1: agent carries the contracts whole ──
for t in test_fail hard_rule_violated ambiguous_spec dep_missing scope_creep_detected; do
  grep -qF "$t" "$AG" || fail "1: halt type $t missing from the agent"
done
grep -qF 'scope_creep_detected' "$AG" && ok "1: all 5 halt types in the agent" || true
if grep -qF 'missing_dependency' "$AG"; then fail "1: missing_dependency alias leaked into the agent"; else ok "1: canonical dep_missing only (no alias)"; fi
grep -qF 'bolt_self_report:' "$AG" && ok "1: bolt_self_report: template in the agent (exact key)" || fail "1: bolt_self_report: missing"
grep -qF 'confidence: <0.0-1.0>' "$AG" && grep -qF 'uncertain_decisions' "$AG" && grep -qF 'retry_history' "$AG" \
  && ok "1: self-report keys complete (confidence / uncertain_decisions / retry_history)" || fail "1: self-report keys incomplete"
for st in composer_dep_added git_branch_created file_partially_written; do
  grep -qF "$st" "$AG" || fail "1: step_type enum value $st missing from the agent"
done
grep -qF 'file_partially_written' "$AG" && ok "1: step_type enum spot-checks present" || true
grep -qF 'step_id' "$AG" && grep -qF 'compensating_action' "$AG" && grep -qF 'idempotent' "$AG" \
  && ok "1: rollback-hint schema fields present" || fail "1: rollback schema incomplete"
grep -qF 'partial-state-and-saga.md' "$AG" && ok "1: full-taxonomy pointer kept" || fail "1: saga pointer lost"
grep -qF 'Generated by mega-sdd execute-bolts' "$AG" && ok "1: provenance marker string byte-identical in the agent" || fail "1: provenance marker missing/drifted"
grep -qF 'whitelist_violation' "$AG" && ok "1: B3 observer sentence appended (whitelist_violation)" || fail "1: B3 sentence missing"
grep -qF 'provenance_missing' "$AG" && ok "1: trailer-missing halt named in the agent" || fail "1: provenance_missing halt missing"

# ── 4: validator key strings unchanged ──
grep -qF '"Generated by mega-sdd execute-bolts" not in head' "$VBA" \
  && ok "4: validator provenance marker key unchanged" || fail "4: validator marker key drifted"
grep -qF '"bolt_self_report:" not in content' "$VBA" \
  && ok "4: validator self-report key unchanged" || fail "4: validator self-report key drifted"
grep -qF 'agents/bolt-implementer.md' "$VBA" && ok "4: validator comment names the new contract home" || fail "4: validator comment stale"

if [ "$FAILED" -eq 0 ]; then echo "ALL P2D PINS OK"; exit 0; else echo "P2D pins FAILED"; exit 1; fi
