#!/usr/bin/env bash
# test-p2b-stamp-binding.sh — batch2 P2b, as merged in v7 Fase 2 (group 2):
# the binding.md static boilerplate (banner + enum legend) is stamped by
# derive-binding-json.sh PHASE 0 — the model never types it, and the stamp is
# parser-invisible.
#
#   1  EMPIRICAL: one derive run on a model-shaped binding.md (no banner/legend)
#      → banner is the first line after frontmatter; legend under `## Conflicts`
#   2  idempotent: second run → binding.md byte-identical
#   3  CRITICAL: binding.json byte-identical whether the md is stamped or not
#      (banner + legend sit outside every binding_md.py-read region) — proven
#      by hand-stripping the stamped blocks and re-deriving
#   4  zero-conflict binding.md (no ## Conflicts heading) → banner stamped,
#      legend skipped gracefully, exit 0
#   5  keterangan pins: the 4-code gloss single-sources in the derive script;
#      the template names the arrangement (Enum legend note + DISPLAYER line)
#
# Run: bash tests/boilerplate-diet/test-p2b-stamp-binding.sh
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
P="${ROOT}/plugins/mega-sdd"
DERIVE="$P/scripts/derive-binding-json.sh"
BMT="$P/skills/bind-codebase/references/binding-md-template.md"
SKILL="$P/skills/bind-codebase/SKILL.md"

FAILED=0
ok()   { printf '  \342\234\223 %s\n' "$*"; }
fail() { printf '  \342\234\227 FAIL: %s\n' "$*"; FAILED=1; }
WORK="$(mktemp -d 2>/dev/null || mktemp -d -t p2b)"
trap 'rm -rf "$WORK"' EXIT

[ -f "$DERIVE" ] || { echo "missing $DERIVE"; exit 1; }

echo "== P2b: binding boilerplate is stamped, parser-invisible =="

# ── model-shaped fixture (what Step 4 writes: NO banner, NO legend) ──
write_fixture() {
cat > "$1/binding.md" <<'EOF'
---
vault: ./vault
codebase_map: ./codebase-map.md
bound_at: 2026-07-19T00:00:00Z
strict: false
binding_metadata:
  codebase_map_provenance: snapshot-verified
  head: abc1234
---

# Binding Manifest

## Summary
- claims_total: 2
- confirmed: 1
- conflict: 1
- oq: 0

## Confirmed Claims (1)
- C-001 | 03-data-model.md:12 | app/Models/User.php:10 | User has an email field

## Implementation State Map (2 — ALWAYS 6 columns; the Field diff cell is `n/a` unless precision_tier: ast)
| Claim ID | Verdict | State | Anchor | Confidence | Field diff |
|---|---|---|---|---|---|
| C-001 | CONFIRMED | IMPLEMENTED | app/Models/User.php:10 | high | (exact match) |
| C-002 | CONFLICT | UNKNOWN | app/Models/Order.php:5 | low | n/a |

## Conflicts (1) — BLOCKING

### CONFLICT-1 — order total type drift
- **Vault claim**: Order.total is integer cents
- **Codebase reality**: Order.total is a float column (app/Models/Order.php:5)
- **Claim**: C-002
- **Vault doc**: 03-data-model.md §Order
- **Codebase artifact**: app/Models/Order.php
- **conflict_class**: signature-drift
- **resolution_complexity**: low
- **Verdict**: CONFLICT (BLOCKING)
- **Suggested action**: KEEP_CODE — code reality wins (app/Models/Order.php:5)

## Open Questions (0)
| ID | Question | Source | Auto-resolve attempted |
|---|---|---|---|
EOF
}

V="$WORK/v1"; mkdir -p "$V"; write_fixture "$V"

# ── 1: one derive run stamps (phase 0) AND derives ──
bash "$DERIVE" --vault "$V" </dev/null >/dev/null 2>&1; RC=$?
[ "$RC" -eq 0 ] && ok "1: derive (phase-0 stamp) exits 0" || fail "1: derive/stamp failed (rc=$RC)"
cp "$V/binding.json" "$WORK/stamped.json" 2>/dev/null || fail "1: binding.json missing"
grep -qF 'REGENERATED by bind-codebase on every run' "$V/binding.md" && ok "1: banner stamped" || fail "1: banner missing after stamp"
# banner is the first line after the frontmatter
AFTER_FM="$(awk 'f==2{print; exit} /^---$/{f++}' "$V/binding.md")"
case "$AFTER_FM" in "> REGENERATED by bind-codebase"*) ok "1: banner is the first line after frontmatter";; *) fail "1: banner not first after frontmatter (got: ${AFTER_FM:0:60})";; esac
grep -qF 'Enum legend (keterangan contract' "$V/binding.md" && ok "1: legend stamped" || fail "1: legend missing after stamp"
# the four keterangan glosses must LAND in the stamped artifact — pinning only
# the script source would stay green if the insertion logic dropped them
grep -qF 'KEEP_VAULT = the vault is right' "$V/binding.md" \
  && grep -qF 'KEEP_CODE = the vault is wrong' "$V/binding.md" \
  && grep -qF 'DEFER = downgraded to an OQ' "$V/binding.md" \
  && grep -qF 'SPLIT = the claim is split into sub-claims' "$V/binding.md" \
  && ok "1: all 4 keterangan gloss lines land in the STAMPED binding.md" \
  || fail "1: a keterangan gloss line is missing from the stamped binding.md"
# legend sits under the ## Conflicts heading, before the first detail heading
python3 - "$V/binding.md" <<'PYEOF' && ok "1: legend sits under ## Conflicts before the first ### CONFLICT heading" || fail "1: legend misplaced"
import sys
md = open(sys.argv[1]).read()
c = md.find("## Conflicts")
l = md.find("Enum legend (keterangan contract")
d = md.find("### CONFLICT-1")
sys.exit(0 if 0 <= c < l < d else 1)
PYEOF

# ── 2: idempotent ──
cp "$V/binding.md" "$WORK/stamped-1.md"
bash "$DERIVE" --vault "$V" </dev/null >/dev/null 2>&1; RC=$?
[ "$RC" -eq 0 ] && cmp -s "$WORK/stamped-1.md" "$V/binding.md" \
  && ok "2: second run leaves binding.md byte-identical (stamp idempotent)" || fail "2: stamp not idempotent (rc=$RC)"

# ── 3: parser-invisibility — strip the stamped blocks, re-derive, same json ──
V3="$WORK/v3"; mkdir -p "$V3"; write_fixture "$V3"   # unstamped model shape
bash "$DERIVE" --vault "$V3" </dev/null >/dev/null 2>&1
A=$(python3 -c "import json,sys; d=json.load(open('$WORK/stamped.json')); d.pop('generated_at',None); d.pop('vault',None); print(json.dumps(d,sort_keys=True))")
B=$(python3 -c "import json,sys; d=json.load(open('$V3/binding.json')); d.pop('generated_at',None); d.pop('vault',None); print(json.dumps(d,sort_keys=True))")
[ "$A" = "$B" ] \
  && ok "3: binding.json identical from stamped and freshly-stamped fixtures (stamp is parser-invisible)" \
  || fail "3: binding.json diverges — stamp leaked into a parsed region"

# ── 4: zero-conflict binding.md → banner only, graceful legend skip ──
V2="$WORK/v2"; mkdir -p "$V2"; write_fixture "$V2"
python3 - "$V2/binding.md" <<'PYEOF'
import sys
p = sys.argv[1]
md = open(p).read()
md = md[: md.find("## Conflicts")] + md[md.find("## Open Questions") :]
open(p, "w").write(md)
PYEOF
bash "$DERIVE" --vault "$V2" </dev/null >/dev/null 2>&1; RC=$?
[ "$RC" -eq 0 ] && ok "4: zero-conflict derive/stamp exits 0 (never blocks a clean bind)" || fail "4: zero-conflict derive failed (rc=$RC)"
grep -qF 'REGENERATED by bind-codebase on every run' "$V2/binding.md" && ok "4: banner stamped on zero-conflict file" || fail "4: banner missing (zero-conflict)"
if grep -qF 'Enum legend (keterangan contract' "$V2/binding.md"; then fail "4: legend stamped despite no ## Conflicts heading"; else ok "4: legend skipped gracefully (no ## Conflicts heading)"; fi

# ── 5: keterangan single-source + template arrangement (v7: in the derive) ──
grep -qF 'KEEP_VAULT = the vault is right' "$DERIVE" && grep -qF 'KEEP_CODE = the vault is wrong' "$DERIVE" \
  && grep -qF 'DEFER = downgraded to an OQ' "$DERIVE" && grep -qF 'SPLIT = the claim is split into sub-claims' "$DERIVE" \
  && ok "5: all 4 code glosses live in derive-binding-json.sh (single source)" || fail "5: gloss text missing from the derive script"
grep -qF 'the DISPLAYER' "$DERIVE" && ok "5: script legend keeps the Tier-3/DISPLAYER story" || fail "5: DISPLAYER line missing from script legend"
grep -qF 'Enum legend (keterangan contract' "$BMT" && grep -qF 'the DISPLAYER' "$BMT" \
  && ok "5: template authoring notes keep the keterangan pins" || fail "5: template keterangan note lost"
grep -qF 'derive-binding-json.sh` PHASE 0' "$BMT" && ok "5: template names the stamping phase" || fail "5: template does not name the stamping phase"
grep -qF "PHASE 0 stamps" "$SKILL" && ok "5: bind SKILL documents the phase-0 stamp inside the derive Run" || fail "5: SKILL phase-0 stamp note missing"

if [ "$FAILED" -eq 0 ]; then echo "ALL P2B PINS OK"; exit 0; else echo "P2B pins FAILED"; exit 1; fi
