#!/usr/bin/env bash
# test-p2d-agent-contracts.sh — batch2 P2d (spec 2026-07-19-batch2-derive-and-diet.md):
# the four constant dispatch blocks (halt vocabulary, self-report template, rollback
# schema, provenance trailer shape) move from the per-dispatch prompt template into
# agents/bolt-implementer.md (the system-prompt M-09 precedent) — single source,
# marker strings byte-identical, per-dispatch prompt carries pointer + values.
#
#   1  agent carries the moved blocks whole (all 5 halt types, self-report keys,
#      step_type enum, trailer marker, whitelist_violation) — canonical vocab only
#   2  dispatch template no longer carries the constants (negative pins) but carries
#      the Contracts pointer and the Provenance values block. The Legacy dispatch
#      (order-3) inline instruction was RETIRED 2026-07-31 by tranche 2b; the pin is
#      inverted to guard the closure, not deleted.
#   3  context-enrichment T1 list updated; the load-bearing caps (cap_hard, cap_t2)
#      unchanged; cap_t1 pinned to its 2026-07-31 measured amendment
#   4  validate-bolt-artifacts.sh key strings unchanged (marker + bolt_self_report:)
#
# Run: bash tests/boilerplate-diet/test-p2d-agent-contracts.sh
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
P="${ROOT}/plugins/mega-sdd"
AG="$P/agents/bolt-implementer.md"
BP="$P/skills/execute-bolts/references/bolt-dispatch-prompt.md"
CE="$P/skills/execute-bolts/references/context-enrichment.md"
SB="$P/skills/execute-bolts/references/superpowers-bridge.md"
SK="$P/skills/execute-bolts/SKILL.md"
VBA="$P/scripts/validate-bolt-artifacts.sh"

FAILED=0
ok()   { printf '  \342\234\223 %s\n' "$*"; }
fail() { printf '  \342\234\227 FAIL: %s\n' "$*"; FAILED=1; }

echo "== P2d: dispatch constants are agent-carried, single source =="

# ── 1: agent carries the contracts whole ──
for t in test_fail hard_rule_violated ambiguous_spec dep_missing scope_creep_detected; do
  grep -qF "$t" "$AG" || fail "1: halt type $t missing from the agent"
done
grep -qF 'scope_creep_detected' "$AG" && ok "1: all 5 halt types in the agent" || true
if grep -qF 'missing_dependency' "$AG"; then fail "1: missing_dependency alias leaked into the agent"; else ok "1: canonical dep_missing only (no alias)"; fi
grep -qF 'bolt_self_report:' "$AG" && ok "1: bolt_self_report: template in the agent (exact key)" || fail "1: bolt_self_report: missing"
grep -qF 'confidence: <0.0-1.0>' "$AG" && grep -qF 'uncertain_decisions' "$AG" && grep -qF 'retry_history' "$AG" \
  && ok "1: self-report keys complete (confidence / uncertain_decisions / retry_history)" || fail "1: self-report keys incomplete"
for st in composer_dep_added git_branch_created file_partially_written; do
  grep -qF "$st" "$AG" || fail "1: step_type enum value $st missing from the agent"
done
grep -qF 'file_partially_written' "$AG" && ok "1: step_type enum spot-checks present" || true
grep -qF 'step_id' "$AG" && grep -qF 'compensating_action' "$AG" && grep -qF 'idempotent' "$AG" \
  && ok "1: rollback-hint schema fields present" || fail "1: rollback schema incomplete"
grep -qF 'partial-state-and-saga.md' "$AG" && ok "1: full-taxonomy pointer kept" || fail "1: saga pointer lost"
grep -qF 'Generated by mega-sdd execute-bolts' "$AG" && ok "1: provenance marker string byte-identical in the agent" || fail "1: provenance marker missing/drifted"
grep -qF 'whitelist_violation' "$AG" && ok "1: B3 observer sentence appended (whitelist_violation)" || fail "1: B3 sentence missing"
grep -qF 'provenance_missing' "$AG" && ok "1: trailer-missing halt named in the agent" || fail "1: provenance_missing halt missing"

# ── 2: dispatch template diet + pointer ──
for neg in retry_history compensating_action; do
  if grep -qF "$neg" "$BP"; then fail "2: constant block residue '$neg' survives in the dispatch template"; fi
done
grep -qF 'retry_history' "$BP" || ok "2: constant blocks gone from the dispatch template"
grep -qF 'carried by your system prompt (agents/bolt-implementer.md' "$BP" \
  && ok "2: Contracts pointer line (name + version) present" || fail "2: Contracts pointer missing"
grep -qF 'plugin.json version at dispatch' "$BP" && ok "2: version resolved from plugin.json at dispatch" || fail "2: version source missing"
grep -qF 'Provenance values' "$BP" && grep -qF 'vault_sha256' "$BP" \
  && ok "2: per-dispatch Provenance values block present" || fail "2: Provenance values block missing"
# The order-3 legacy-dispatch element was REMOVED 2026-07-31 (tranche 2b): the builder and
# agents/bolt-implementer.md ship in the SAME plugin tree, so "first-class agents unavailable
# while the builder ran" is unreachable. This assertion is INVERTED rather than deleted — it now
# pins the closure, so a future pass cannot quietly restore an inline-the-contracts fallback that
# would tell a generic executor its system prompt carries contracts it does not hold.
if grep -qF 'Legacy dispatch (order-3 fallback ONLY' "$BP"; then
  fail "2: retired order-3 legacy-dispatch element resurfaced in the dispatch template"
else
  grep -qF 'order-3 legacy-dispatch element is REMOVED' "$BP" \
    && grep -qF 'Legacy path — CLOSED' "$SB" \
    && ok "2: order-3 legacy dispatch closed, and closure recorded in BOTH surfaces" \
    || fail "2: order-3 removed but its closure is not recorded in template + bridge"
fi
# test-pinned per-dispatch sections stay
grep -qF '## Design system (UI-bearing unit' "$BP" && grep -qF 'Acceptance-test provenance NOTE' "$BP" \
  && grep -qF 'Reuse index' "$BP" && ok "2: test-pinned dynamic sections untouched" || fail "2: a pinned dynamic section was dropped"

# ── 3: context-enrichment T1 list + caps ──
grep -qF 'Contracts pointer line' "$CE" && ok "3: T1 lists the contracts pointer" || fail "3: T1 contracts-pointer entry missing"
grep -qF 'Provenance values block' "$CE" && ok "3: T1 lists the provenance values block" || fail "3: T1 values entry missing"
if grep -qF 'Halt vocabulary block' "$CE"; then fail "3: stale T1 'Halt vocabulary block' entry survives"; else ok "3: stale T1 constant entries gone"; fi
# `cap_hard` and `cap_t2` are the LOAD-BEARING caps and are still pinned unchanged: cap_hard is
# term (b) of the dispatch_prompt_too_large conjunction, and cap_t2 is what triggers the truncation
# cascade. `cap_t1` moved 2048 -> 12288 on 2026-07-31 by a measured amendment (§AMENDMENT in
# context-enrichment.md, n=123 runs): T1 is never truncated and the unit body is verbatim, so no
# value of cap_t1 bounds anything — it is a REPORTING THRESHOLD, and 2048 was satisfiable only when
# the framework-pack content was missing. Pinned to the amended value, with the amendment itself
# pinned alongside so the number can never drift without its justification.
grep -qF 'cap_hard:      12288' "$CE" && grep -qF 'cap_t2:        10240' "$CE" \
  && ok "3: load-bearing caps unchanged (cap_hard = halt term b, cap_t2 = cascade trigger)" || fail "3: load-bearing caps drifted"
grep -qF 'cap_t1:        12288' "$CE" && grep -qF 'AMENDMENT 2026-07-31' "$CE" \
  && ok "3: cap_t1 carries its measured amendment" || fail "3: cap_t1 drifted from its amendment"
grep -qF 'agent-carried' "$SK" && ok "3: execute-bolts SKILL states the agent-carried contracts" || fail "3: SKILL wording stale"

# ── 4: validator key strings unchanged ──
grep -qF '"Generated by mega-sdd execute-bolts" not in head' "$VBA" \
  && ok "4: validator provenance marker key unchanged" || fail "4: validator marker key drifted"
grep -qF '"bolt_self_report:" not in content' "$VBA" \
  && ok "4: validator self-report key unchanged" || fail "4: validator self-report key drifted"
grep -qF 'agents/bolt-implementer.md' "$VBA" && ok "4: validator comment names the new contract home" || fail "4: validator comment stale"

if [ "$FAILED" -eq 0 ]; then echo "ALL P2D PINS OK"; exit 0; else echo "P2D pins FAILED"; exit 1; fi
