#!/usr/bin/env bash
# test-binding-done-rule.sh — pins the done rule of the real writer (write-unit-binding.sh via
# rebind-units.sh; _lib/unit_binding.py). A unit whose bolt-report says `status: success` is DONE,
# so its create claim is carried forward and never re-verdicted, UNLESS its OWN bolts dir holds a
# legacy dispatch-prompt.md with no postflight.json (a pre-P3 run that never reached post-flight).
# File mtimes (which git does not keep) and other vaults' leftovers never decide it.
# Fixture: U-001 creates docs/alpha.md; bound while absent, built by its own bolt commit, then a
# user commit edits the file. Re-verdicted, that file is CONFLICT (ALREADY_EXISTS).
# Run: bash tests/v9/test-binding-done-rule.sh </dev/null
set -u
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"; S="$ROOT/plugins/mega-sdd/scripts"
T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT; export HOME="$T/home"; mkdir -p "$HOME"
rc=0; ok() { echo "PASS: $1"; }; bad() { echo "FAIL: $1"; rc=1; }
G() { git -C "$1" -c user.name=t -c user.email=t@t -c commit.gpgsign=false "${@:2}"; }
V=".mega-sdd/vaults/demo"; F="$T/base"; mkdir -p "$F/$V/units" "$F/docs"
printf '# r\n' > "$F/README.md"; printf '# Context — demo\n' > "$F/$V/context.md"; printf '{"vault_layout": 3}\n' > "$F/$V/vault.json"
cat > "$F/$V/units/U-001.md" <<'EOF'
---
id: U-001
title: Alpha page
task_type: create
context_source: context.md#f-1
depends_on: []
target_files:
  - path: docs/alpha.md
    operation: create
acceptance_test:
  - type: test
    command: test -f docs/alpha.md && echo U-001-ok
    expects: "U-001-ok"
---
# U-001 — Alpha page
EOF
rb() { bash "$S/rebind-units.sh" --cwd="$1" --vault="$1/$V" --units=U-001 >/dev/null 2>&1; }
cl() { python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print([(c["verdict"], c.get("carried_forward")) for c in d["claims"]])' "$1/$V/bolts/U-001/binding.json" 2>/dev/null; }
( cd "$F" && git init -q . ) && G "$F" add -A && G "$F" commit -qm "chore: seed"; rb "$F"
[ "$(cl "$F")" = "[('CONFIRMED', None)]" ] || bad "setup: the first bind of an absent create target is not CONFIRMED: $(cl "$F")"
printf '<!-- Generated by mega-sdd execute-bolts 9.0.0\n     Unit: U-001 · provenance: unit -->\n# Alpha\n' > "$F/docs/alpha.md"
G "$F" add docs && G "$F" commit -qm "feat(U-001): Alpha page" -m "Unit: U-001"
printf -- '---\nunit: U-001\nstatus: success\n---\n# Bolt Report — U-001\n' > "$F/$V/bolts/U-001/bolt-report.md"
printf 'a user edit\n' >> "$F/docs/alpha.md"; G "$F" commit -qam "docs: tweak the alpha page"
case_() { rm -rf "$T/$1"; cp -R "$F" "$T/$1"; }
DONE="[('CONFIRMED', 'done unit')]"

case_ c1; rb "$T/c1"
[ "$(cl "$T/c1")" = "$DONE" ] && ok "c1: no leftover → done, the create claim is carried forward (CONFIRMED)" || bad "c1: $(cl "$T/c1")"

case_ c2; B="$T/c2/$V/bolts/U-001"; printf '# dispatch\n' > "$B/dispatch-prompt.md"; printf '{"status":"pass"}\n' > "$B/postflight.json"
python3 -c 'import os,sys; os.utime(sys.argv[1], (1000, 1000)); os.utime(sys.argv[2], (2000, 2000))' "$B/postflight.json" "$B/dispatch-prompt.md"
rb "$T/c2"
[ "$(cl "$T/c2")" = "$DONE" ] && ok "c2: a legacy dispatch-prompt.md with a postflight.json → done, whatever the mtimes (a checkout rewrites them)" || bad "c2: $(cl "$T/c2")"

case_ c3; printf '# dispatch\n' > "$T/c3/$V/bolts/U-001/dispatch-prompt.md"; rb "$T/c3"
[ "$(cl "$T/c3")" = "[('CONFLICT', None)]" ] && ok "c3: a legacy dispatch-prompt.md with no postflight.json → still in its run, re-verdicted (CONFLICT)" || bad "c3: $(cl "$T/c3")"

case_ c4; mkdir -p "$T/c4/.mega-sdd/vaults/other/bolts/U-001"; printf '# dispatch\n' > "$T/c4/.mega-sdd/vaults/other/bolts/U-001/dispatch-prompt.md"; rb "$T/c4"
[ "$(cl "$T/c4")" = "$DONE" ] && ok "c4: another vault's same-id leftover does not decide this unit → done" || bad "c4: $(cl "$T/c4")"

echo; [ "$rc" -eq 0 ] && echo "binding done rule: ALL PASS" || echo "binding done rule: FAILED"; exit "$rc"
