#!/usr/bin/env bash
# test-inline-lane.sh — P2 lean inline execution (spec docs/superpowers/specs/2026-09-27-v9-simplification-design.md
# §8): `execute-bolts` (inline since §8.5; `--agents` retired, §8.6) runs units in ONE context; the CONFLICT gate runs at run start (derive-exec-plan.sh,
# which resumes an open run until --retire) plus a re-bind at each task; the run-boundary gate `conflict_bypassed`
# (validate-bolt-artifacts.sh --conflict-bypass-scan) catches an honest controller's slip — a unit committed past an
# open CONFLICT, a quarantine (its own or a depends_on ancestor's) or a skipped re-bind, judged by the state it landed
# under. Deliberate evasion is out of scope (spec §8.2) and is not tested here.
# Fixture F: U-001 claims lib/config.js (exists); U-002 → U-001; U-003 claims a missing path (a real CONFLICT); U-004
# → U-003 (commented inline list); U-005 → U-004 (commented block list); U-006 independent. F2 create→modify→verify;
# F3 two vaults, colliding ids; F4 a docs/mega-sdd vault, nested unit. Sections: a --pending · b no bind · c run-start
# gate, open run · d the plan · e retire, quarantine paths · k F2 · f the scan · g the hook · m episodes, own_wip,
# rebind_skipped, own_wip at the close, done rule, a literal run · h wiring + docs.   Run: bash tests/v9/test-inline-lane.sh </dev/null
set -u
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"; P="$ROOT/plugins/mega-sdd"; S="$P/scripts"
DEP="$S/derive-exec-plan.sh"; VBA="$S/validate-bolt-artifacts.sh"
rc=0; ok() { echo "PASS: $1"; }; bad() { echo "FAIL: $1"; rc=1; }
T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT; export HOME="$T/home"; mkdir -p "$HOME"
G() { git -C "$1" -c user.name=t -c user.email=t@t -c commit.gpgsign=false "${@:2}"; }
J() { python3 -c 'import json,sys; d=json.loads(sys.argv[1]); print(eval(sys.argv[2], {"d": d}))' "$1" "$2" 2>/dev/null; }
JF() { python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print(eval(sys.argv[2], {"d": d}))' "$1" "$2" 2>/dev/null; }
mkunit() { # <vault> <id> <title> <target> <depends_on line(s)> [extra body] [task_type] [operation]
  mkdir -p "$1/units"
  cat > "$1/units/$2.md" <<EOF
---
id: $2
title: $3
task_type: ${7:-create}
context_source: context.md#f-1
$5
target_files:
  - path: $4
    operation: ${8:-create}
acceptance_test:
  - type: test
    command: test -f $4 && echo $2-ok
    expects: "$2-ok"
---
# $2 — $3

BODY-SENTINEL-$2 the plan points at this file and never inlines it.
${6:-}
EOF
}
brief() { # replica of superpowers task-brief's extractor (fence-aware Task-heading awk)
  awk -v n="$2" '
    /^```/ { infence = !infence }
    !infence && /^#+[ \t]+Task[ \t]+[0-9]+/ { intask = ($0 ~ ("^#+[ \t]+Task[ \t]+" n "([^0-9]|$)")) }
    intask { print }' "$1"
}
bolt() { # <root> <unit> <path> <title> [v5] — a canonical bolt commit (provenance header + trailers)
  mkdir -p "$(dirname "$1/$3")"
  printf '<!-- Generated by mega-sdd execute-bolts 9.0.0\n     Unit: %s · provenance: unit -->\n# %s\n' "$2" "$4" > "$1/$3"
  G "$1" add "$3" && G "$1" commit -qm "feat($2): $4" -m "Unit: $2
SDD-PROVENANCE: mega-sdd/execute-bolts unit=$2${5:+
SDD-Acceptance: v5}"
}
report() { # <vault> <unit> <root> <path> — a minimal bolt-report (orphan gate quiet)
  mkdir -p "$1/bolts/$2"
  printf -- '---\nunit: %s\nstatus: success\ncommits: [%s]\ntarget_hashes:\n  %s: %s\n---\n# Bolt Report — %s\n\nbolt_self_report:\n  confidence: 0.9\n' \
    "$2" "$(git -C "$3" rev-parse --short HEAD)" "$4" "$(shasum -a 256 "$3/$4" | cut -d' ' -f1)" "$2" > "$1/bolts/$2/bolt-report.md"
}
evid() { bash "$S/run-acceptance-tests.sh" --cwd="$1" --unit="$2" --quiet >/dev/null 2>&1; bash "$S/run-postflight-scan.sh" --cwd="$1" --unit="$2" --quiet >/dev/null 2>&1; }
scanat() { bash "$VBA" --cwd="$1" --conflict-bypass-scan --quiet >/dev/null 2>&1; echo $?; }
issues() { JF "$1/.mega-sdd/.bolt-conflict-bypass-state.json" 'sorted({(i["unit_id"], i.get("via")) for i in d["issues"]})'; }
reasons() { JF "$1/.mega-sdd/.bolt-conflict-bypass-state.json" 'sorted({(i["unit_id"], i.get("reason")) for i in d["issues"]})'; }
clone() { rm -rf "$T/$1"; cp -R "$F" "$T/$1"; }
ins() { python3 -c 'import sys; p, a, b = sys.argv[1:4]; t = open(p).read(); open(p, "w").write(t.replace(a + "\n", a + "\n" + b + "\n", 1))' "$@"; }
claim() { printf '\n## Claims\n- C-%s-01 "the legacy adapter exists" — expect: lib/legacy.js — must-exist' "$(printf '%s' "$1" | tr -d -)"; }
census() { # the plan-coverage census is not under test here; stand it in through the census library's own key + digest
  python3 - "$1" "$S/_lib" <<'PYC'
import glob, json, os, sys
root, lib = sys.argv[1], sys.argv[2]; sys.path.insert(0, lib)
doc = {"status": "PASS"}
try:
    import prd_headings as ph
    doc["vaults"] = {ph.vault_key(root, v): {"status": "PASS", "sources": [], "digest": ph.digest(root, v, [])}
                     for v in sorted(glob.glob(os.path.join(root, ".mega-sdd", "vaults", "*")))}
except Exception:
    pass
json.dump(doc, open(os.path.join(root, ".mega-sdd", ".plan-coverage-state.json"), "w"))
PYC
}

# ── fixture F ────────────────────────────────────────────────────────────────
F="$T/proj"; V="$F/.mega-sdd/vaults/demo"; mkdir -p "$V/units" "$F/docs" "$F/lib"
printf '# demo\n' > "$F/README.md"; printf 'module.exports = {};\n' > "$F/lib/config.js"
printf '# Context — demo\n\n## Flows\n- F-1 docs pages\n' > "$V/context.md"; printf '{"vault_layout": 3}\n' > "$V/vault.json"
mkunit "$V" U-001 "Alpha page" docs/alpha.md "depends_on: []" '
## Claims
- C-U001-01 "the config module exists" — expect: lib/config.js — must-exist'
mkunit "$V" U-002 "Beta page" docs/beta.md "depends_on: [U-001]"
mkunit "$V" U-003 "Gamma page" docs/gamma.md "depends_on: []" "$(claim U-003)"
mkunit "$V" U-004 "Delta page" docs/delta.md "depends_on: [U-003]     # waits for the gamma page"
mkunit "$V" U-005 "Epsilon page" docs/epsilon.md "depends_on:
  - U-004   # delta first"
mkunit "$V" U-006 "Zeta page" docs/zeta.md "depends_on: []"
( cd "$F" && git init -q . ) && G "$F" add -A && G "$F" commit -qm "chore: seed"
SEED="$(git -C "$F" rev-parse HEAD)"; census "$F"
dep() { bash "$DEP" --cwd="$F" --vault="$V" --retire >/dev/null 2>&1; bash "$DEP" --cwd="$F" --vault="$V" "$@" 2>"$T/dep.err"; }   # a fresh run
depat() { local r="$1"; shift; bash "$DEP" --cwd="$r" --vault="$r/.mega-sdd/vaults/demo" --retire >/dev/null 2>&1; bash "$DEP" --cwd="$r" --vault="$r/.mega-sdd/vaults/demo" "$@" 2>"$T/dep.err"; }
scan() { scanat "$F"; }; SST="$F/.mega-sdd/.bolt-conflict-bypass-state.json"
plans() { ls "$V/bolts/" 2>/dev/null | grep -cE '^_(exec-plan|inline-ledger)' ; }
qr() { J "$1" '[(q["unit"], q["reason"], q.get("via") or q.get("freshness") or q.get("conflict_ids")) for q in d["quarantined"]]'; }

# ── a: --pending ─────────────────────────────────────────────────────────────
OUT="$(dep --pending)"; R=$?
[ $R -eq 0 ] && [ "$(J "$OUT" 'd["pending"]')" = "['U-001', 'U-002', 'U-003', 'U-004', 'U-005', 'U-006']" ] \
  && ok "a1: --pending lists every not-done unit in topo order (ties by id)" || bad "a1: rc=$R out=$OUT err=$(head -c 200 "$T/dep.err")"
[ "$(plans)" = 0 ] && [ ! -e "$V/bolts" ] && ok "a2: --pending writes nothing" || bad "a2: --pending wrote $(ls "$V/bolts" 2>/dev/null)"
cp "$V/units/U-004.md" "$T/u4.bak"; ins "$V/units/U-004.md" "task_type: create" "status: superseded"
[ "$(J "$(dep --pending)" 'd["pending"]')" = "['U-001', 'U-002', 'U-003', 'U-005', 'U-006']" ] && ok "a3: a status: superseded unit is not pending" || bad "a3: $(dep --pending)"
cp "$T/u4.bak" "$V/units/U-004.md"

# ── b: no bind ran → the dispatch gate's freshness check quarantines every candidate ──
OUT="$(dep)"; R=$?
[ $R -eq 1 ] && [ "$(J "$OUT" 'sorted({(q["reason"], q.get("freshness")) for q in d["quarantined"] if "via" not in q})')" = "[('binding_stale', 'binding_absent')]" ] \
  && [ "$(J "$OUT" 'd["plan"]')" = "None" ] && [ "$(plans)" = 0 ] && ok "b: no binding.json → binding_stale (binding_absent, the run-start freshness check), exit 1, no plan" || bad "b: rc=$R out=$OUT"
[ "$(scan)" = 0 ] && [ "$(JF "$SST" 'd["status"]')" = "PASS" ] && ok "f0: units but no bolt commit → PASS" || bad "f0: $(head -c 300 "$SST" 2>/dev/null)"

# ── c: the up-front bind, then the plan ──────────────────────────────────────
RB="$(bash "$S/rebind-units.sh" --cwd="$F" --vault="$V" --units="$(J "$(dep --pending)" '",".join(d["pending"])')" 2>/dev/null | tail -1)"
[ "$(J "$RB" 'd["conflicts"]')" = "1" ] && ok "c0: rebind-units --units=<pending> binds all six (1 CONFLICT, from the real writer)" || bad "c0: $RB"
OUT="$(dep)"; R=$?; PLAN="$(J "$OUT" 'd["plan"]')"
[ $R -eq 0 ] && [ "$(J "$OUT" 'd["schema"]')" = "exec-plan/1" ] && [ "$(J "$OUT" 'd["in_scope"]')" = "['U-001', 'U-002', 'U-006']" ] \
  && ok "c1: exit 0 with quarantines; in_scope [U-001, U-002, U-006] in topo order" || bad "c1: rc=$R out=$OUT err=$(head -c 300 "$T/dep.err")"
[ "$(qr "$OUT")" = "[('U-003', 'binding_conflict', ['C-U003-01']), ('U-004', 'depends_on_quarantined', 'U-003'), ('U-005', 'depends_on_quarantined', 'U-004')]" ] \
  && ok "c2: U-003 binding_conflict C-U003-01; U-004 via U-003 and U-005 via U-004 (commented depends_on, transitive)" || bad "c2: $(qr "$OUT")"
[ "$PLAN" = "$V/bolts/_exec-plan-$(git -C "$F" rev-parse HEAD | cut -c1-12).md" ] && [ -f "$PLAN" ] && ok "c3: plan at <vault>/bolts/_exec-plan-<head12>.md" || bad "c3: $PLAN"
[ "$(J "$OUT" 'd["halt"]')" = "None" ] && [ "$(J "$OUT" 'd["run_base"]')" = "$SEED" ] && ok "c4: halt null; run_base is the full HEAD" || bad "c4: $OUT"
RU="$(bash "$S/derive-ready-units.sh" --cwd="$F" --vault="$V" 2>/dev/null)"
[ "$(J "$RU" 'sorted((b["unit"], tuple(b["waiting_on"])) for b in d["blocked"])')" = "[('U-002', ('U-001',)), ('U-004', ('U-003',)), ('U-005', ('U-004',))]" ] \
  && ok "c5: derive-ready-units (the default path) reads a commented depends_on too" || bad "c5: $RU"
[ "$(head -1 "$V/bolts/_inline-ledger-$(git -C "$F" rev-parse HEAD | cut -c1-12).md" 2>/dev/null)" = "# inline ledger — plan: $PLAN" ] && ok "c6: the built-in ledger (identity line) is written with the plan (F1/I1)" || bad "c6: $(ls "$V/bolts")"
cp "$PLAN" "$T/plan.c1"; mv "$V/bolts/U-002/binding.json" "$T/b2x.json"; OUT="$(bash "$DEP" --cwd="$F" --vault="$V" 2>/dev/null)"; R=$?; mv "$T/b2x.json" "$V/bolts/U-002/binding.json"
[ $R -eq 0 ] && [ "$(J "$OUT" '(d.get("resumed"), d["plan"], d["in_scope"])')" = "(True, '$PLAN', ['U-001', 'U-002', 'U-006'])" ] && cmp -s "$PLAN" "$T/plan.c1" \
  && ok "c7: an open plan is returned (resumed), never regenerated — (b) re-run mid-task cannot re-plan the run (F1/I1)" || bad "c7: rc=$R $OUT"

# ── d: the plan is superpowers-compatible and carries the run's rules ────────
if [ -f "$PLAN" ]; then
  B1="$(brief "$PLAN" 1)"; B2="$(brief "$PLAN" 2)"
  GC="$(sed -n '/## Global Constraints/,/## Review Focus/p' "$PLAN")"; RF="$(sed -n '/## Review Focus/,/^---$/p' "$PLAN")"
  case "$B1" in "## Task 1: U-001 — Alpha page"*) ok "d1: task 1 brief starts at its heading" ;; *) bad "d1: $(printf '%s' "$B1" | head -2)" ;; esac
  printf '%s' "$B2" | grep -q 'U-002' && ! printf '%s' "$B2" | grep -qE 'U-006|units/U-001' && ! printf '%s' "$B1" | grep -q 'U-002' \
    && ok "d2: each task brief carries its own unit only" || bad "d2: $(printf '%s' "$B2" | grep -n 'U-00' | head -5)"
  HEADS="$(awk '/^```/ { f = !f } !f && /^#+[ \t]+Task[ \t]+[0-9]+/ { print }' "$PLAN")"
  [ "$(printf '%s\n' "$HEADS" | grep -cE '^## Task [123]: U-00[126] — ')" = 3 ] && [ "$(printf '%s\n' "$HEADS" | grep -c .)" = 3 ] && [ -z "$(brief "$PLAN" 4)" ] \
    && ok "d3: exactly three task headings outside a fence" || bad "d3: $HEADS"
  for s in 'finishing-a-development-branch' 'SDD-Acceptance: v5' 'SDD-PROVENANCE: mega-sdd/execute-bolts unit=' 'Generated by mega-sdd execute-bolts' \
           'delivery-check.sh' 'test script' 'Navigation' 'scaffold' 'Empty env' 'wiring' 'U-003' 'U-004' 'U-005' 'main/master' 'no worktree' \
           ':(exclude).mega-sdd' '[DESCRIPTION]' 'no ledger' 'Ruling' 'hard_rule_violated' 'STOPS THE RUN' 'fix(U-XXX)' 'fix(review)' 'never `-A`' \
           'chore(sdd): evidence U-XXX'; do
    grep -qF -- "$s" "$PLAN" && ok "d4: plan carries: $s" || bad "d4: plan lacks: $s"
  done
  grep -qE '^mega-sdd-trace:execute-bolts$' "$PLAN" && ok "d5: the reviewer trace line stands on its own line" || bad "d5: no own-line trace"
  AF="$(sed -n '/^## After the last task/,$p' "$PLAN" | tr '\n' ' ')"; BL="$(brief "$PLAN" 3)"
  printf '%s' "$GC" | grep -F 'Final review and Finishing' | grep -qF '## After the last task' \
    && printf '%s' "$AF" | grep -qE "run-full-suite\.sh.*--base=$SEED.*$SEED\.\.HEAD.*Close: reviewed.*delivery-check\.sh.*run-full-suite\.sh.*--rebind-wip.*evidence run.*conflict-bypass-scan.*--retire" \
    && ok "d6: the close order is inline-run (d): suite, review, fixes, Close: reviewed, delivery-check, suite again, re-bind, evidence, gate, retire" || bad "d6: $AF"
  ! grep -q 'bolt_introduces_locked_drift' "$PLAN" && ok "d16: the plan names no STOP no step can raise (no task runs the per-bolt drift check)" || bad "d16: locked-drift STOP in the plan"
  printf '%s' "$BL" | grep -q '^## After the last task' && printf '%s' "$BL" | grep -qE '^mega-sdd-trace:execute-bolts$' && ! printf '%s' "$B1" | grep -q 'After the last' \
    && ok "d15: the last task's brief carries the close, so a compacted controller keeps the overrides (I4)" || bad "d15: $(printf '%s' "$BL" | tail -3)"
  printf '%s' "$RF" | grep -F 'Out of scope' | grep -q 'U-003' && ok "d7: Review Focus names the quarantined units out of scope" || bad "d7: $RF"
  grep -q 'BODY-SENTINEL' "$PLAN" && bad "d8: the unit body is inlined" || ok "d8: the unit body is pointed at, never inlined"
  grep -qF '$BASE' "$PLAN" && bad "d9: an unset \$BASE in the plan" || ok "d9: no unset \$BASE in the plan"
  for n in 1 2; do
    u="U-00$n"; b="$(brief "$PLAN" $n | sed "s/\.sh' /.sh /g")"
    for s in "$V/units/$u.md" "rebind-units.sh --cwd=$F --vault=$V --units=$u" "run-preflight-scan.sh --cwd=$F --unit=$u" \
             "run-acceptance-tests.sh --cwd=$F --unit=$u" "run-postflight-scan.sh --cwd=$F --unit=$u" "run-code-gates.sh --cwd=$F --base=<BASE>" \
             "--unit=$V/units/$u.md --write" "bolt-report.md" "Unit: $u" "**Task done:**" "**Depends on:**" "_inline-ledger-" "chore(sdd): evidence $u"; do
      printf '%s' "$b" | grep -qF -- "$s" && ok "d10: task $n carries: $s" || bad "d10: task $n lacks: $s"
    done
  done
  printf '%s' "$B2" | grep -qE '^\*\*Depends on:\*\* U-001' && ok "d11: task 2 names its depends_on" || bad "d11: $(printf '%s' "$B2" | grep Depends)"
  printf '%s' "$B1" | grep -qF '2/3/4/5/6/8' && printf '%s' "$B1" | grep -qE 'exit 2: STOP the run' && printf '%s' "$B1" | grep -qF 'hard_rule_violated: STOP the run' \
    && ok "d12: every fatal exit an Expected line names is a STOP" || bad "d12: $(printf '%s' "$B1" | grep -n 'Expected: exit' | head -4)"
  printf '%s' "$B1" | grep -qF '"own_wip": true' && printf '%s' "$B1" | grep -qE 'write-unit-quarantine\.sh.*--unit=U-001 --halt=binding_conflict.*--dependents=' \
    && printf '%s' "$B1" | grep -qF 'go on with the next task' \
    && ok "d13: the re-bind step: own uncommitted target = in progress; a CONFLICT quarantines the unit, skips dependents, continues (K2)" || bad "d13: $(printf '%s' "$B1" | sed -n '/Step 1/,/Step 2/p')"
  printf '%s' "$B1" | grep -qE '^git add -- ' && ! grep -qE '^git add -A' "$PLAN" && ok "d14: commits stage by explicit pathspec, never -A" || bad "d14: $(grep -n 'git add' "$PLAN" | head -3)"
else
  bad "d: no plan to inspect"
fi

# ── e: the quarantine paths ──────────────────────────────────────────────────
WS="$F/.superpowers/sdd/$(basename "$PLAN" .md)"; mkdir -p "$WS"; printf '%s\n' "${PLAN#"$F/"}" > "$WS/plan-path"; clone c2
bash "$DEP" --cwd="$F" --vault="$V" --retire >/dev/null 2>&1; R=$?
[ $R -eq 0 ] && [ "$(plans)" = 0 ] && [ ! -e "$WS" ] && ok "e0: --retire removes the run's plan, ledger and superpowers workspace (the close's last step, C2/F2)" || bad "e0: rc=$R $(ls "$V/bolts") $(ls "$WS" 2>&1)"
bash "$S/write-unit-binding.sh" --cwd="$T/c2" --vault="$T/c2/.mega-sdd/vaults/demo" --unit=U-003 --resolve=C-U003-01=KEEP_CODE --by=user >/dev/null 2>&1
R1="$(J "$(bash "$DEP" --cwd="$T/c2" --vault="$T/c2/.mega-sdd/vaults/demo" 2>/dev/null)" 'd["in_scope"]')"; bash "$DEP" --cwd="$T/c2" --vault="$T/c2/.mega-sdd/vaults/demo" --retire >/dev/null 2>&1
[ "$R1" = "['U-001', 'U-002', 'U-006']" ] && [ "$(J "$(bash "$DEP" --cwd="$T/c2" --vault="$T/c2/.mega-sdd/vaults/demo" 2>/dev/null)" 'd["in_scope"]')" = "['U-001', 'U-002', 'U-003', 'U-004', 'U-005', 'U-006']" ] \
  && ok "e0b: a resolved quarantine waits for the open run; once retired, the next (b) plans it and its dependents (C2)" || bad "e0b: $R1"
mv "$V/bolts/U-002/binding.json" "$T/b2.json"; OUT="$(dep)"; R=$?
[ $R -eq 0 ] && [ "$(qr "$OUT" | grep -c "('U-002', 'binding_stale', 'binding_absent')")" = 1 ] && [ "$(J "$OUT" 'd["in_scope"]')" = "['U-001', 'U-006']" ] \
  && ok "e1: a unit without binding.json is quarantined (binding_absent), the rest proceed" || bad "e1: rc=$R $OUT"
mv "$T/b2.json" "$V/bolts/U-002/binding.json"; OUT="$(dep --units=U-003,U-004)"; R=$?
[ $R -eq 1 ] && [ "$(J "$OUT" 'd["plan"]')" = "None" ] && [ "$(plans)" = 0 ] && [ "$(J "$OUT" '(d["halt"] or {}).get("type")')" = "binding_conflict" ] \
  && J "$OUT" 'd["halt"]["keterangan"]' | grep -q . && ok "e2: every candidate blocked by a CONFLICT → halt binding_conflict with a keterangan, exit 1, stale plans removed" || bad "e2: rc=$R $OUT"
OUT="$(dep --units=U-002)"; R=$?
[ $R -eq 1 ] && [ "$(qr "$OUT")" = "[('U-002', 'depends_on_quarantined', 'U-001')]" ] && [ "$(J "$OUT" 'd["halt"]')" = "None" ] \
  && ok "e3: a dependency neither done nor in scope quarantines the dependent, no halt" || bad "e3: rc=$R $OUT"
printf '# Binding — demo\n\n## Conflicts (1)\n\n### CONFLICT-1 — vault-level contradiction\n- **Verdict**: CONFLICT (BLOCKING)\n' > "$V/binding.md"
OUT="$(dep)"; R=$?
[ $R -eq 1 ] && [ "$(J "$OUT" 'd["halt"]["type"]')" = "binding_conflict" ] && [ "$(J "$OUT" 'd["plan"]')" = "None" ] \
  && ok "e4: a validator drop with no unit_id halts the whole run (binding_conflict)" || bad "e4: rc=$R $OUT"
rm -f "$V/binding.md"; cp "$V/units/U-001.md" "$T/u1.bak"; sed -i.x 's/^depends_on: \[\]$/depends_on: [U-002]/' "$V/units/U-001.md"; rm -f "$V/units/U-001.md.x"
dep >/dev/null; R=$?; dep --pending >/dev/null; R2=$?
[ $R -eq 2 ] && [ $R2 -eq 2 ] && grep -qi 'cycle' "$T/dep.err" && ok "e5: a depends_on cycle → exit 2 with a message (also --pending)" || bad "e5: rc=$R/$R2"
cp "$T/u1.bak" "$V/units/U-001.md"; bash "$DEP" --cwd="$F" >/dev/null 2>&1; [ $? -eq 2 ] && ok "e6: usage (no --vault) → exit 2" || bad "e6: usage exit"
clone cs; printf 'beta\n' > "$T/cs/docs/beta.md"; G "$T/cs" add docs/beta.md && G "$T/cs" commit -qm "chore: hand-written beta"
[ "$(qr "$(depat "$T/cs")" | grep -c "('U-002', 'binding_stale', 'binding_stale')")" = 1 ] && ok "e7: a binding a later non-unit commit made stale → binding_stale (the dispatch gate's function)" || bad "e7: $(depat "$T/cs")"
clone cx; printf '{not json' > "$T/cx/.mega-sdd/vaults/demo/bolts/U-006/binding.json"
[ "$(qr "$(depat "$T/cx")" | grep -c "('U-006', 'binding_conflict'")" = 1 ] && ok "e9: an unparseable binding at run start → binding_conflict (fail closed)" || bad "e9: $(depat "$T/cx")"
dep >/dev/null

# ── k: F2 — create → modify → verify ─────────────────────────────────────────
F2="$T/p2"; V2="$F2/.mega-sdd/vaults/demo"
mkunit "$V2" U-001 'Add `slugify` helper for $HOME paths' src/slugify.js "depends_on: []"
mkunit "$V2" U-002 "Extend slugify" src/slugify.js "depends_on: [U-001]" "" modify modify
cat > "$V2/units/U-003.md" <<'EOF'
---
id: U-003
title: Verify slugify
task_type: verify
depends_on: [U-002]
target_files: []
acceptance_test:
  - type: test
    command: grep -q extended src/slugify.js && echo v-ok
    expects: "v-ok"
---
# U-003
EOF
printf '# Context\n' > "$V2/context.md"; printf '{"vault_layout": 3}\n' > "$V2/vault.json"; printf '# p2\n' > "$F2/README.md"; ( cd "$F2" && git init -q . ) && G "$F2" add -A && G "$F2" commit -qm "chore: seed"
bash "$S/rebind-units.sh" --cwd="$F2" --vault="$V2" --units=U-001,U-002,U-003 >/dev/null 2>&1
OUT="$(bash "$DEP" --cwd="$F2" --vault="$V2" 2>/dev/null)"; R=$?; PLAN2="$(J "$OUT" 'd["plan"]')"
[ $R -eq 0 ] && [ "$(J "$OUT" 'd["in_scope"]')" = "['U-001', 'U-002', 'U-003']" ] && [ "$(J "$OUT" 'd.get("deferred")')" = "{'U-002': ['C-U002-A01']}" ] \
  && ok "k1: a modify of what an in-scope ancestor creates is deferred to its task re-bind, not quarantined" || bad "k1: rc=$R $OUT"
if [ -f "$PLAN2" ]; then
  B3="$(brief "$PLAN2" 3)"
  lr="$(printf '%s\n' "$B3" | grep -n 'Write the bolt report' | head -1 | cut -d: -f1)"; lc="$(printf '%s\n' "$B3" | grep -n 'Step [0-9]*: Commit' | head -1 | cut -d: -f1)"
  le="$(printf '%s\n' "$B3" | grep -n 'Record the evidence' | head -1 | cut -d: -f1)"
  [ -n "$lr" ] && [ -n "$lc" ] && [ -n "$le" ] && [ "$lr" -lt "$lc" ] && [ "$lc" -lt "$le" ] \
    && ok "k2: a verify task writes the bolt report, commits it, then records evidence" || bad "k2: report=$lr commit=$lc evidence=$le"
  brief "$PLAN2" 2 | grep -qF 'the deferred C-U002-A01 re-verdicts' && ok "k3: the deferred claim is named in its task's re-bind step" || bad "k3: no deferred note"
  mkdir -p "$F2/src"; printf 'module.exports = s => s;\n' > "$F2/src/slugify.js"
  awk '/^```bash$/ { f = 1; next } /^```$/ { if (f) exit } f' <(brief "$PLAN2" 1) > "$T/commit1.sh"
  ( cd "$F2" && GIT_AUTHOR_NAME=t GIT_AUTHOR_EMAIL=t@t GIT_COMMITTER_NAME=t GIT_COMMITTER_EMAIL=t@t bash "$T/commit1.sh" >/dev/null 2>&1 )
  [ "$(git -C "$F2" log -1 --format=%s)" = 'feat(U-001): Add `slugify` helper for $HOME paths' ] \
    && ok "k4: the plan's commit block keeps backticks and \$ literal" || bad "k4: subject=$(git -C "$F2" log -1 --format=%s)"
  evid "$F2" U-001; report "$V2" U-001 "$F2" src/slugify.js
else
  bad "k: no F2 plan"
fi
# the task re-bind skipped: U-002 commits in the same second as its binding while the deferred CONFLICT is
# open — but its claim held at the commit's parent (U-001 created the file)
GEN2="$(JF "$V2/bolts/U-002/binding.json" 'd["generated_at"]')"
printf 'module.exports = s => s; // extended\n' > "$F2/src/slugify.js"
GIT_AUTHOR_DATE="$GEN2" GIT_COMMITTER_DATE="$GEN2" G "$F2" commit -qam "feat(U-002): Extend slugify" -m "Unit: U-002"
[ "$(scanat "$F2")" = 0 ] && ok "k5: a commit inside an open CONFLICT whose claim held at the commit's parent is not a bypass" || bad "k5: $(reasons "$F2")"
bash "$S/rebind-units.sh" --cwd="$F2" --vault="$V2" --units=U-002 >/dev/null 2>&1
[ "$(scanat "$F2")" = 0 ] && ok "k6: the re-bind that re-verdicts it CONFIRMED stays PASS" || bad "k6: $(reasons "$F2")"
bash "$S/rebind-units.sh" --cwd="$F2" --vault="$V2" --units=U-003 >/dev/null 2>&1
RS="$(bash "$DEP" --cwd="$F2" --vault="$V2" 2>/dev/null)"; bash "$DEP" --cwd="$F2" --vault="$V2" --retire >/dev/null 2>&1; NPLAN="$(J "$(bash "$DEP" --cwd="$F2" --vault="$V2" 2>/dev/null)" 'd["plan"]')"
[ -n "$PLAN2" ] && [ "$(J "$RS" '(d.get("resumed"), d["plan"])')" = "(True, '$PLAN2')" ] && [ "$NPLAN" != "$PLAN2" ] && [ -f "$NPLAN" ] && [ ! -e "$PLAN2" ] \
  && [ "$(ls "$V2/bolts" | grep -cE '^_(exec-plan|inline-ledger)')" = 2 ] && ok "k7: a later HEAD resumes the open plan (no re-plan mid-run); after --retire a new plan + ledger (F1, C2)" || bad "k7: $RS new=$NPLAN"
mkdir -p "$V2/bolts/U-003"; printf -- '---\nunit: U-003\nstatus: success\ntarget_hashes: {}\n---\n# U-003\n' > "$V2/bolts/U-003/bolt-report.md"
G "$F2" add -f "$V2/bolts/U-003/bolt-report.md" && G "$F2" commit -qm "chore(U-003): Verify slugify" -m "Unit: U-003"
bash "$S/run-acceptance-tests.sh" --cwd="$F2" --unit=U-003 --quiet >/dev/null 2>&1
[ "$(J "$(bash "$DEP" --cwd="$F2" --vault="$V2" --pending 2>/dev/null)" '"U-003" in d["pending"]')" = "False" ] && ok "k8: a completed verify unit is not pending again" || bad "k8"

# ── f: the conflict_bypassed run-boundary gate ───────────────────────────────
[ "$(scan)" = 0 ] && [ "$(JF "$SST" 'd["mode"]')" = "conflict-bypass-scan" ] && ok "f1: no bolt commit → PASS (mode conflict-bypass-scan)" || bad "f1: $(head -c 300 "$SST")"
sleep 1; bolt "$F" U-001 docs/alpha.md "Alpha page" v5; evid "$F" U-001; report "$V" U-001 "$F" docs/alpha.md
[ "$(scan)" = 0 ] && ok "f2: a bolt of a unit with no open CONFLICT → PASS" || bad "f2: $(reasons "$F")"
[ "$(J "$(dep --pending)" 'd["pending"]')" = "['U-002', 'U-003', 'U-004', 'U-005', 'U-006']" ] && ok "f3: --pending drops the done unit" || bad "f3: $(dep --pending)"
sleep 1; G "$F" rm -q lib/config.js && G "$F" commit -qm "chore: drop the config module"
bash "$S/rebind-units.sh" --cwd="$F" --vault="$V" --units=U-001 >/dev/null 2>&1
[ "$(JF "$V/bolts/U-001/binding.json" '[c["id"] for c in d["claims"] if c["verdict"] == "CONFLICT" and not c.get("resolution")]')" = "['C-U001-01']" ] \
  && [ "$(scan)" = 0 ] && ok "f4: a CONFLICT a sync re-bind opens on a DONE unit after its commits is not a bypass" || bad "f4: $(reasons "$F")"
bash "$S/rebind-units.sh" --cwd="$F" --vault="$V" --units=U-002 >/dev/null 2>&1
OUT="$(dep --units=U-002)"; R=$?
[ $R -eq 0 ] && [ "$(J "$OUT" 'd["in_scope"]')" = "['U-002']" ] && [ "$(J "$OUT" 'd["done"]')" = "['U-001']" ] && ok "f5: a done dependency lets the dependent run" || bad "f5: rc=$R $OUT"
sleep 1; bolt "$F" U-002 docs/beta.md "Beta page" v5; evid "$F" U-002; report "$V" U-002 "$F" docs/beta.md
[ "$(scan)" = 0 ] && ok "f6: the dependent of a done unit whose CONFLICT opened later passes (both ends agree)" || bad "f6: $(issues "$F")"
clone cb; sleep 1; G "$T/cb" rebase -q --force-rebase "$SEED" >/dev/null 2>&1
[ "$(scanat "$T/cb")" = 0 ] && ok "f7: a rebase of implemented units is not a bypass (author time)" || bad "f7: $(issues "$T/cb")"
clone cq; bash "$S/write-unit-quarantine.sh" --cwd="$T/cq" --vault="$T/cq/.mega-sdd/vaults/demo" --unit=U-006 --halt=spec_contradiction --reason="spec X, code Y" >/dev/null 2>&1
[ "$(qr "$(depat "$T/cq" --units=U-006)")" = "[('U-006', 'quarantine_recorded', None)]" ] && ok "f8: a recorded quarantine is kept out of the plan" || bad "f8: $(depat "$T/cq" --units=U-006)"
sleep 1; bolt "$T/cq" U-006 docs/zeta.md "Zeta page"
[ "$(scanat "$T/cq")" = 1 ] && [ "$(reasons "$T/cq")" = "[('U-006', 'quarantined')]" ] && ok "f9: a commit of a quarantined unit (a forgotten quarantine) → FAIL" || bad "f9: $(reasons "$T/cq")"
bash "$S/write-unit-quarantine.sh" --cwd="$T/cq" --vault="$T/cq/.mega-sdd/vaults/demo" --unit=U-006 --release --by=user >/dev/null 2>&1
[ "$(scanat "$T/cq")" = 0 ] && ok "f10: released by the human → PASS" || bad "f10: $(reasons "$T/cq")"
sleep 1; bolt "$F" U-003 docs/gamma.md "Gamma page"; report "$V" U-003 "$F" docs/gamma.md
[ "$(scan)" = 1 ] && [ "$(JF "$SST" '[(i["halt_type"], i["reason"], i["conflict_ids"], len(i["commit"]), bool(i["commit_time"])) for i in d["issues"]]')" = "[('conflict_bypassed', 'open_conflict', ['C-U003-01'], 40, True)]" ] \
  && ok "f11: a U-003 commit past its open CONFLICT → FAIL conflict_bypassed (id, commit, commit_time)" || bad "f11: $(head -c 600 "$SST")"
grep -q 'resolve-oq --binding' "$SST" && grep -qi 'keterangan' "$SST" && ! grep -qi 'revert' "$SST" && ok "f12: next_action names the human remedy with a keterangan, never a revert" || bad "f12: $(JF "$SST" 'd["next_action"]')"
bolt "$F" U-004 docs/delta.md "Delta page"; report "$V" U-004 "$F" docs/delta.md
bolt "$F" U-005 docs/epsilon.md "Epsilon page"; report "$V" U-005 "$F" docs/epsilon.md
[ "$(scan)" = 1 ] && [ "$(issues "$F")" = "[('U-003', None), ('U-004', 'U-003'), ('U-005', 'U-003')]" ] \
  && ok "f13: dependents committed past the open CONFLICT → FAIL via U-003, U-005 too (transitive, commented depends_on)" || bad "f13: $(issues "$F")"

# ── g: the hook reads the state; the state file is guarded ───────────────────
hook() { printf '%s' "$1" | ( cd "$F" && bash "$P/hooks/pre-tool-use" 2>/dev/null ); }
deny() { case "$1" in *'"permissionDecision": "deny"'*) return 0 ;; esac; return 1; }
pj() { python3 -c 'import json,sys; print(json.dumps({"session_id":"sess-inline-0001","cwd":sys.argv[1],"tool_name":sys.argv[2],"tool_input":json.loads(sys.argv[3])}))' "$F" "$1" "$2"; }
pjf() { python3 -c 'import json,sys; print(json.dumps({"session_id":"sess-inline-0001","cwd":sys.argv[1],"tool_name":sys.argv[2],"tool_input":{"file_path":sys.argv[3],"content":"{}","old_string":"a","new_string":"b"}}))' "$F" "$1" "$2"; }
census "$F"
SKILL_P="$(pj Skill '{"skill":"mega-sdd:execute-bolts","args":"--all --lite --inline"}')"
O="$(hook "$SKILL_P")"
case "$O" in *'"permissionDecision": "deny"'*conflict-bypass*'U-003 open_conflict'*'U-004 depends_on_blocked via U-003'*) ok "g1: Skill execute-bolts DENIED on a FAIL bypass state, naming each unit's reason" ;;
  *) bad "g1: $(printf '%s' "$O" | head -c 600)" ;; esac
for tool in Write Edit; do
  deny "$(hook "$(pjf $tool "$SST")")" && ok "g3: $tool of the bypass state is denied" || bad "g3: $tool allowed"
done
for c in "rm .mega-sdd/.bolt-conflict-bypass-state.json" "echo '{}' > .mega-sdd/.bolt-conflict-bypass-state.json"; do
  deny "$(hook "$(pj Bash "$(python3 -c 'import json,sys; print(json.dumps({"command": sys.argv[1]}))' "$c")")")" && ok "g4: Bash '$c' is denied" || bad "g4: Bash '$c' allowed"
done
O="$(hook "$(pjf Write "$F/.mega-sdd/.bolt-acceptance-state.json")")"
case "$O" in *'"permissionDecision": "deny"'*bolt-conflict-bypass*) ok "g5: the Write/Edit block message enumerates bolt-conflict-bypass" ;; *) bad "g5: $(printf '%s' "$O" | head -c 300)" ;; esac
rm -f "$F/.mega-sdd/.stop-scan-stamp" "$SST"
printf '{"session_id":"sess-inline-0001","cwd":"%s","hook_event_name":"Stop"}' "$F" | ( cd "$F" && bash "$P/hooks/stop" >/dev/null 2>&1 )
[ "$(JF "$SST" 'd["status"]')" = "FAIL" ] && ok "g6: the Stop hook writes the FAIL bypass state" || bad "g6: $(head -c 300 "$SST" 2>/dev/null)"

# ── f (cont.): a re-bind never clears it; the human decision does ────────────
sleep 1; bash "$S/rebind-units.sh" --cwd="$F" --vault="$V" --units=U-003 >/dev/null 2>&1
[ "$(scan)" = 1 ] && [ "$(issues "$F")" = "[('U-003', None), ('U-004', 'U-003'), ('U-005', 'U-003')]" ] \
  && ok "f14: a re-bind that keeps the CONFLICT open never clears the bypass, own or via" || bad "f14: $(issues "$F")"
sleep 1; printf 'fix\n' >> "$F/docs/gamma.md"; G "$F" commit -qam "fix(U-003): gamma wording" -m "Unit: U-003"
[ "$(scan)" = 1 ] && ok "f15: a later U-003 commit past the open CONFLICT → FAIL" || bad "f15: $(issues "$F")"
for u in U-003 U-001; do
  for cid in $(JF "$V/bolts/$u/binding.json" '" ".join(c["id"] for c in d["claims"] if c["verdict"] == "CONFLICT" and not c.get("resolution"))'); do
    bash "$S/write-unit-binding.sh" --cwd="$F" --vault="$V" --unit=$u --resolve="$cid=KEEP_CODE" --by=user >/dev/null 2>&1
  done
done
[ "$(scan)" = 0 ] && ok "f16: PASS after the human's write-unit-binding --resolve (own and via released)" || bad "f16: $(issues "$F")"
report "$V" U-003 "$F" docs/gamma.md
deny "$(hook "$SKILL_P")" && bad "g7: Skill still denied with the bypass state PASS" || ok "g7: Skill execute-bolts ALLOWED once the bypass state is PASS"
cp "$V/bolts/U-003/binding.json" "$T/b3.json"
clone cl; printf '{"schema": "unit-binding/1", "unit": "U-003", "claims": [{"id": "C-U003-01", "kind": "fs_must_exist", "expect": "lib/legacy.js", "verdict": "CONFLICT"}]}\n' > "$T/cl/.mega-sdd/vaults/demo/bolts/U-003/binding.json"
[ "$(scanat "$T/cl")" = 0 ] && [ "$(JF "$T/cl/.mega-sdd/.bolt-conflict-bypass-state.json" 'd["legacy_advisory"]')" = "['U-003']" ] \
  && ok "f17: a legacy binding with no CONFLICT time → advisory only, PASS" || bad "f17: $(head -c 400 "$T/cl/.mega-sdd/.bolt-conflict-bypass-state.json")"
printf '{not json' > "$V/bolts/U-003/binding.json"
[ "$(scan)" = 1 ] && [ "$(reasons "$F")" = "[('U-003', 'binding_unparseable')]" ] && ok "f18: an unparseable binding of a bolted unit → FAIL (fail closed)" || bad "f18: $(reasons "$F")"
cp "$T/b3.json" "$V/bolts/U-003/binding.json"
F5="$T/p5"; mkdir -p "$F5/.mega-sdd"; ( cd "$F5" && git init -q . ) && printf 'x\n' > "$F5/a" && G "$F5" add a && G "$F5" commit -qm init
[ "$(scanat "$F5")" = 0 ] && [ "$(JF "$F5/.mega-sdd/.bolt-conflict-bypass-state.json" 'd.get("fast_path")')" = "no_bolt_artifacts" ] && ok "f19: no bolts/U-XXX entry → PASS on the 0-fork fast path" || bad "f19"
F4="$T/p4"; V4="$F4/docs/mega-sdd/vaults/demo"; mkdir -p "$V4/units/U-002"; printf '# c\n' > "$V4/context.md"
mkunit "$V4" U-001 "Gamma" docs/g.md "depends_on: []" "$(claim U-001)"; mkunit "$V4" U-002 "Delta" docs/d.md "depends_on: [U-001]"; mv "$V4/units/U-002.md" "$V4/units/U-002/unit.md"
printf '# p4\n' > "$F4/README.md"; mkdir -p "$F4/.mega-sdd"; ( cd "$F4" && git init -q . ) && G "$F4" add -A && G "$F4" commit -qm seed
bash "$S/rebind-units.sh" --cwd="$F4" --vault="$V4" --units=U-001,U-002 >/dev/null 2>&1
OUT="$(bash "$DEP" --cwd="$F4" --vault="$V4" 2>/dev/null)"
[ "$(qr "$OUT")" = "[('U-001', 'binding_conflict', ['C-U001-01']), ('U-002', 'depends_on_quarantined', 'U-001')]" ] && ok "f20: a docs/mega-sdd vault's CONFLICT unit is quarantined at run start" || bad "f20: $OUT"
sleep 1; bolt "$F4" U-002 docs/d.md "Delta"
[ "$(scanat "$F4")" = 1 ] && [ "$(issues "$F4")" = "[('U-002', 'U-001')]" ] && ok "f21: a nested-layout dependent in a docs/mega-sdd vault → FAIL via U-001" || bad "f21: $(issues "$F4")"
F3="$T/p3"; mkdir -p "$F3/.mega-sdd/vaults"
for vn in alpha beta; do mkdir -p "$F3/.mega-sdd/vaults/$vn"; printf '# c\n' > "$F3/.mega-sdd/vaults/$vn/context.md"; done
mkunit "$F3/.mega-sdd/vaults/alpha" U-001 "Alpha one" docs/a1.md "depends_on: []"; mkunit "$F3/.mega-sdd/vaults/beta" U-001 "Beta one" docs/b1.md "depends_on: []" "$(claim U-001)"
printf '# p3\n' > "$F3/README.md"; ( cd "$F3" && git init -q . ) && G "$F3" add -A && G "$F3" commit -qm seed
for vn in alpha beta; do bash "$S/rebind-units.sh" --cwd="$F3" --vault="$F3/.mega-sdd/vaults/$vn" --units=U-001 >/dev/null 2>&1; done
sleep 1; bolt "$F3" U-001 docs/b1.md "Beta one"
[ "$(scanat "$F3")" = 1 ] && [ "$(JF "$F3/.mega-sdd/.bolt-conflict-bypass-state.json" '[i["vault"] for i in d["issues"]]')" = "['.mega-sdd/vaults/beta']" ] \
  && ok "f22: a colliding unit id is checked in the vault its commit touched" || bad "f22: $(head -c 400 "$F3/.mega-sdd/.bolt-conflict-bypass-state.json")"

# ── m: a commit is judged against the CONFLICT state it landed under ─────────
MK() { rm -rf "$1"; mkdir -p "$1/.mega-sdd/vaults/demo/units" "$1/lib" "$1/docs"; printf '# m\n' > "$1/README.md"; printf 'module.exports = {};\n' > "$1/lib/config.js"
  printf '# Context — demo\n' > "$1/.mega-sdd/vaults/demo/context.md"; printf '{"vault_layout": 3}\n' > "$1/.mega-sdd/vaults/demo/vault.json"; }
MV() { printf '%s/.mega-sdd/vaults/demo' "$1"; }
seed() { ( cd "$1" && git init -q . ) && G "$1" add -A && G "$1" commit -qm "chore: seed"; }
rb() { bash "$S/rebind-units.sh" --cwd="$1" --vault="$(MV "$1")" --units="$2" >/dev/null 2>&1; }
cl() { JF "$(MV "$1")/bolts/$2/binding.json" '[(c["id"], c["verdict"]) for c in d["claims"] if not c.get("resolution")]'; }
resolve() { bash "$S/write-unit-binding.sh" --cwd="$1" --vault="$(MV "$1")" --unit="$2" --resolve="$3=KEEP_CODE" --by=user >/dev/null 2>&1; }
cpx() { rm -rf "$2"; cp -R "$1" "$2"; }
# m1: the bypass commit makes its own CONFLICT claim true; the re-bind that closes it never launders it
M1="$T/m1"; MK "$M1"; mkunit "$(MV "$M1")" U-001 "Legacy adapter" src/legacy.js "depends_on: []" "" modify modify; seed "$M1"; rb "$M1" U-001
[ "$(cl "$M1" U-001)" = "[('C-U001-A01', 'CONFLICT')]" ] && ok "m1a: a modify target that does not exist → CONFLICT C-U001-A01" || bad "m1a: $(cl "$M1" U-001)"
cpx "$M1" "$T/m1s"; sleep 1; bolt "$M1" U-001 src/legacy.js "Legacy adapter"; r1="$(scanat "$M1")"; rb "$M1" U-001
[ "$r1" = 1 ] && [ "$(cl "$M1" U-001)" = "[('C-U001-A01', 'CONFIRMED')]" ] && [ "$(scanat "$M1")" = 1 ] && [ "$(reasons "$M1")" = "[('U-001', 'closed_conflict')]" ] \
  && [ "$(JF "$(MV "$M1")/bolts/U-001/binding.json" '[e["id"] for e in d["conflict_history"]]')" = "['C-U001-A01']" ] \
  && ok "m1b: the re-bind closes the CONFLICT into conflict_history; the commit made while it was open stays a bypass" || bad "m1b: $r1 $(cl "$M1" U-001) $(reasons "$M1")"
resolve "$M1" U-001 C-U001-A01 && [ "$(scanat "$M1")" = 0 ] && ok "m1c: the human decision on the closed episode (write-unit-binding --resolve) releases it" || bad "m1c: $(reasons "$M1")"
ON="$(JF "$(MV "$T/m1s")/bolts/U-001/binding.json" '[c["conflict_since"] for c in d["claims"] if c["id"] == "C-U001-A01"][0]')"
mkdir -p "$T/m1s/src"; printf 'x\n' > "$T/m1s/src/legacy.js"; G "$T/m1s" add src
GIT_AUTHOR_DATE="$ON" GIT_COMMITTER_DATE="$ON" G "$T/m1s" commit -qm "chore: legacy adapter" -m "unit: U-001"
[ "$(scanat "$T/m1s")" = 1 ] && ok "m1d: a commit in the same second the CONFLICT opened counts (>=), a lowercase unit: trailer too (git's parse)" || bad "m1d: $(reasons "$T/m1s")"
M1F="$T/m1f"; MK "$M1F"; mkunit "$(MV "$M1F")" U-001 "Legacy adapter" src/legacy.js "depends_on: []" "" modify modify
mkunit "$(MV "$M1F")" U-002 "Beta page" docs/beta.md "depends_on: [U-001]"; seed "$M1F"; rb "$M1F" U-001,U-002
sleep 1; bolt "$M1F" U-002 docs/beta.md "Beta page"; r1="$(scanat "$M1F")"
sleep 1; mkdir -p "$M1F/src"; printf 'x\n' > "$M1F/src/legacy.js"; G "$M1F" add src && G "$M1F" commit -qm "chore: add the legacy adapter"; rb "$M1F" U-001
[ "$r1" = 1 ] && [ "$(cl "$M1F" U-001)" = "[('C-U001-A01', 'CONFIRMED')]" ] && [ "$(issues "$M1F" | grep -c "('U-002', 'U-001')")" = 1 ] && [ "$(scanat "$M1F")" = 1 ] \
  && ok "m1e: a later re-bind that closes the ancestor's CONFLICT does not release a dependent committed inside it" || bad "m1e: $r1 $(issues "$M1F")"
# m2: a migrated vault (first bind after the commit) passes; an ancestor done only by its own bypass does not release its dependent
M2="$T/m2"; MK "$M2"; mkunit "$(MV "$M2")" U-006 "Zeta page" docs/zeta.md "depends_on: []"; seed "$M2"; sleep 1; bolt "$M2" U-006 docs/zeta.md "Zeta page"; sleep 1; rb "$M2" U-006
[ "$(scanat "$M2")" = 0 ] && ok "m2a: a unit implemented before its first bind (a migrated vault) → PASS" || bad "m2a: $(reasons "$M2")"
M2D="$T/m2d"; MK "$M2D"; mkunit "$(MV "$M2D")" U-003 "Gamma page" docs/gamma.md "depends_on: []" "$(claim U-003)"
mkunit "$(MV "$M2D")" U-004 "Delta page" docs/delta.md "depends_on: [U-003]"; seed "$M2D"; rb "$M2D" U-003,U-004; cpx "$M2D" "$T/m2g"
sleep 1; bolt "$M2D" U-003 docs/gamma.md "Gamma page" v5; evid "$M2D" U-003; report "$(MV "$M2D")" U-003 "$M2D" docs/gamma.md; bolt "$M2D" U-004 docs/delta.md "Delta page"
[ "$(scanat "$M2D")" = 1 ] && [ "$(issues "$M2D")" = "[('U-003', None), ('U-004', 'U-003')]" ] \
  && ok "m2b: an ancestor done only by its own bypass does not release its dependent (implemented BEFORE the block)" || bad "m2b: $(issues "$M2D")"
sleep 1; bolt "$T/m2g" U-003 docs/gamma.md "Gamma page"; sed -i.x 's/C-U003-01/C-U003-02/' "$(MV "$T/m2g")/units/U-003.md"; rm -f "$(MV "$T/m2g")/units/U-003.md.x"; sleep 1; rb "$T/m2g" U-003
[ "$(cl "$T/m2g" U-003 | grep -c "C-U003-02', 'CONFLICT")" = 1 ] && [ "$(scanat "$T/m2g")" = 1 ] && [ "$(JF "$(MV "$T/m2g")/bolts/U-003/binding.json" 'd.get("conflict_history")')" = "None" ] \
  && resolve "$T/m2g" U-003 C-U003-02 && [ "$(scanat "$T/m2g")" = 0 ] \
  && ok "m2c: a renamed claim id keeps its onset (claim key, not id): the bypass stays, and ONE decision on the new id releases it" || bad "m2c: $(cl "$T/m2g" U-003) $(reasons "$T/m2g")"
# m3: a target inserted above the CONFLICT renumbers its minted id (A01→A02); the onset stays
M3="$T/m3"; MK "$M3"; mkunit "$(MV "$M3")" U-001 "Legacy adapter" src/legacy.js "depends_on: []" "" modify modify; seed "$M3"; rb "$M3" U-001
sleep 1; bolt "$M3" U-001 docs/one.md "One"
ins "$(MV "$M3")/units/U-001.md" "target_files:" "  - path: docs/one.md
    operation: create"; sleep 1; rb "$M3" U-001
[ "$(cl "$M3" U-001 | grep -c "C-U001-A02', 'CONFLICT")" = 1 ] && [ "$(scanat "$M3")" = 1 ] && ok "m3: a renumbered CONFLICT keeps its onset; the bypass stays" || bad "m3: $(cl "$M3" U-001) $(reasons "$M3")"
# m4: a human-resolved CONFLICT that a later re-bind re-opens starts a NEW episode
M4="$T/m4"; MK "$M4"; mkunit "$(MV "$M4")" U-007 "Harden config" lib/config.js "depends_on: []" '
## Claims
- C-U007-01 "the config block" — expect: lib/config.js:5-9 — must-exist' modify modify
mkunit "$(MV "$M4")" U-008 "Eta page" docs/eta.md "depends_on: [U-007]"; seed "$M4"; rb "$M4" U-007,U-008; resolve "$M4" U-007 C-U007-01
[ "$(J "$(depat "$M4")" 'd["in_scope"]')" = "['U-007', 'U-008']" ] && ok "m4a: the resolved CONFLICT lets U-007 and U-008 run" || bad "m4a: $(depat "$M4")"
sleep 1; printf '// more\n' >> "$M4/lib/config.js"; G "$M4" commit -qam "feat(U-007): Harden config" -m "Unit: U-007"; bolt "$M4" U-008 docs/eta.md "Eta page"
r1="$(scanat "$M4")"; sleep 1; rb "$M4" U-007,U-008
[ "$r1" = 0 ] && [ "$(JF "$(MV "$M4")/bolts/U-007/binding.json" '[c.get("prior_resolution", {}).get("action") for c in d["claims"] if c["id"] == "C-U007-01" and not c.get("resolution")]')" = "['KEEP_CODE']" ] \
  && [ "$(scanat "$M4")" = 0 ] && ok "m4b: commits made while the CONFLICT was resolved are not a bypass once a re-bind re-opens it" || bad "m4b: $r1 $(reasons "$M4")"
# m5: 'done ancestor' = the done evidence, not "any commit of the ancestor"; the walk window does not decide it
M5="$T/m5"; MK "$M5"; mkunit "$(MV "$M5")" U-003 "Gamma page" docs/gamma.md "depends_on: []" "$(claim U-003)"; mkunit "$(MV "$M5")" U-004 "Delta page" docs/delta.md "depends_on: [U-003]"
seed "$M5"; bolt "$M5" U-003 docs/gamma.md "Gamma scaffold"; G "$M5" rm -q docs/gamma.md && G "$M5" commit -qm "chore: drop the gamma scaffold"
sleep 1; rb "$M5" U-003,U-004; sleep 1; bolt "$M5" U-004 docs/delta.md "Delta page"
[ "$(scanat "$M5")" = 1 ] && [ "$(issues "$M5")" = "[('U-004', 'U-003')]" ] && ok "m5a: an ancestor with a stray early commit but not done still blocks its dependent" || bad "m5a: $(reasons "$M5")"
M6="$T/m6"; MK "$M6"; mkunit "$(MV "$M6")" U-001 "Alpha page" docs/alpha.md "depends_on: []" '
## Claims
- C-U001-01 "the config module exists" — expect: lib/config.js — must-exist'
mkunit "$(MV "$M6")" U-002 "Beta page" docs/beta.md "depends_on: [U-001]"; seed "$M6"; rb "$M6" U-001,U-002
sleep 1; bolt "$M6" U-001 docs/alpha.md "Alpha page" v5; evid "$M6" U-001; report "$(MV "$M6")" U-001 "$M6" docs/alpha.md
for i in $(seq 1 301); do G "$M6" commit -q --allow-empty -m "chore: filler $i"; done
sleep 1; G "$M6" rm -q lib/config.js && G "$M6" commit -qm "chore: drop config"; rb "$M6" U-001; sleep 1; rb "$M6" U-002; bolt "$M6" U-002 docs/beta.md "Beta page" v5
[ "$(scanat "$M6")" = 0 ] && ok "m5b: a done ancestor older than the 300-commit window still counts as done" || bad "m5b: $(reasons "$M6")"
# m6: resume — own uncommitted work (untracked + this unit's provenance header) is `own_wip`; a user's untracked file is not (C1)
M9="$T/m9"; MK "$M9"; mkunit "$(MV "$M9")" U-002 "Beta page" docs/beta.md "depends_on: []"; seed "$M9"; rb "$M9" U-002; cpx "$M9" "$T/m9u"
sleep 1; printf '<!-- Generated by mega-sdd execute-bolts 9.0.0\n     Unit: U-002 · provenance: x -->\n# beta (wip)\n' > "$M9/docs/beta.md"; rb "$M9" U-002
[ "$(JF "$(MV "$M9")/bolts/U-002/binding.json" '[(c["id"], c["verdict"], c.get("own_wip")) for c in d["claims"]]')" = "[('C-U002-A01', 'CONFLICT', True)]" ] \
  && [ "$(J "$(depat "$M9")" 'd["in_scope"]')" = "['U-002']" ] && ok "m6a: a resume re-bind over its own WIP = CONFLICT own_wip, never a run-start quarantine (F1)" || bad "m6a: $(cl "$M9" U-002) $(depat "$M9")"
sleep 1; bolt "$M9" U-002 docs/beta.md "Beta page"; r1="$(scanat "$M9")"; report "$(MV "$M9")" U-002 "$M9" docs/beta.md; sleep 1; rb "$M9" U-002
[ "$r1" = 0 ] && [ "$(cl "$M9" U-002)" = "[('C-U002-A01', 'CONFIRMED')]" ] && [ "$(scanat "$M9")" = 0 ] \
  && ok "m6b: the commit is no bypass, and once done the own_wip CONFLICT re-binds CONFIRMED — never carried forward (F3/I2)" || bad "m6b: $r1 $(cl "$M9" U-002) $(reasons "$M9")"
sleep 1; printf 'user wip\n' > "$T/m9u/docs/beta.md"; rb "$T/m9u" U-002; r1="$(qr "$(depat "$T/m9u")")"; sleep 1; bolt "$T/m9u" U-002 docs/beta.md "Beta page"
[ "$r1" = "[('U-002', 'binding_conflict', ['C-U002-A01'])]" ] && [ "$(scanat "$T/m9u")" = 1 ] && [ "$(reasons "$T/m9u")" = "[('U-002', 'open_conflict')]" ] \
  && ok "m6c: a user's untracked file at a create target, the quarantine forgotten → FAIL open_conflict (C1)" || bad "m6c: $r1 $(reasons "$T/m9u")"
M9C="$T/m9c"; MK "$M9C"; mkunit "$(MV "$M9C")" U-002 "Beta page" docs/beta.md "depends_on: []"; printf '# beta by hand\n' > "$M9C/docs/beta.md"
seed "$M9C"; rb "$M9C" U-002; sleep 1; bolt "$M9C" U-002 docs/beta.md "Beta page"
[ "$(scanat "$M9C")" = 1 ] && ok "m6d: a create target that existed before the unit's first commit is a real ALREADY_EXISTS bypass" || bad "m6d: $(reasons "$M9C")"
# m7: a quarantine and its dependent; an unreadable quarantine time counts from forever
M10="$T/m10"; MK "$M10"; mkunit "$(MV "$M10")" U-006 "Zeta page" docs/zeta.md "depends_on: []"; mkunit "$(MV "$M10")" U-008 "Eta page" docs/eta.md "depends_on: [U-006]"
seed "$M10"; rb "$M10" U-006,U-008; bash "$S/write-unit-quarantine.sh" --cwd="$M10" --vault="$(MV "$M10")" --unit=U-006 --halt=spec_contradiction --reason="X vs Y" >/dev/null 2>&1
cpx "$M10" "$T/m10c"; sleep 1; bolt "$M10" U-006 docs/zeta.md "Zeta page"; bolt "$M10" U-008 docs/eta.md "Eta page"
[ "$(scanat "$M10")" = 1 ] && [ "$(reasons "$M10")" = "[('U-006', 'quarantined'), ('U-008', 'depends_on_blocked')]" ] && ok "m7a: a quarantined unit and its dependent committed → FAIL" || bad "m7a: $(reasons "$M10")"
python3 -c 'import json,sys; p=sys.argv[1]; d=json.load(open(p)); d["quarantined_at"]="garbage"; json.dump(d, open(p,"w"))' "$(MV "$T/m10c")/bolts/U-006/quarantine.json"
sleep 1; bolt "$T/m10c" U-006 docs/zeta.md "Zeta page"
[ "$(scanat "$T/m10c")" = 1 ] && ok "m7b: a quarantine with an unreadable time counts from forever (fail closed)" || bad "m7b: $(reasons "$T/m10c")"
# m8: deferral needs an in-scope creator
M12="$T/m12"; MK "$M12"; mkunit "$(MV "$M12")" U-001 "Slug helper" src/x.js "depends_on: []"
mkunit "$(MV "$M12")" U-002 "Extend slug" src/x.js "depends_on: [U-001]" "" modify modify; mkunit "$(MV "$M12")" U-006 "Zeta page" docs/zeta.md "depends_on: []"
seed "$M12"; rb "$M12" U-001,U-002,U-006; bash "$S/write-unit-quarantine.sh" --cwd="$M12" --vault="$(MV "$M12")" --unit=U-001 --halt=spec_contradiction --reason="X vs Y" >/dev/null 2>&1
sleep 1; bolt "$M12" U-006 docs/zeta.md "Zeta page" v5; rb "$M12" U-006
OUT="$(depat "$M12")"
[ "$(qr "$OUT" | grep -c "('U-002', 'binding_conflict', 'U-001')")" = 1 ] && [ "$(J "$OUT" 'd["deferred"]')" = "{}" ] \
  && ok "m8a: a CONFLICT on a path only a quarantined ancestor would create is not deferred" || bad "m8a: $OUT"
[ "$(J "$OUT" '"U-006" in d["in_scope"]')" = "True" ] && ok "m8b: a bolted, re-bound unit stays in scope" || bad "m8b: $OUT"
# m10: a skipped task re-bind — the unit landed on a tree where its bound claim no longer held, no bind saw that tree (I3)
M14="$T/m14"; MK "$M14"; mkunit "$(MV "$M14")" U-006 "Drop config" lib/config.js "depends_on: []" "" create delete
mkunit "$(MV "$M14")" U-007 "Use config" docs/u7.md "depends_on: []" "$(claim U-007 | sed 's|lib/legacy.js|lib/config.js|')"; seed "$M14"; rb "$M14" U-006,U-007
sleep 1; G "$M14" rm -q lib/config.js && G "$M14" commit -qm "feat(U-006): Drop config" -m "Unit: U-006"; bolt "$M14" U-007 docs/u7.md "Use config"
[ "$(scanat "$M14")" = 1 ] && [ "$(reasons "$M14")" = "[('U-007', 'rebind_skipped')]" ] && ok "m10: a skipped task re-bind (claim broken by an earlier unit) → FAIL rebind_skipped (I3)" || bad "m10: $(reasons "$M14")"
# m11: the close re-binds every unit whose binding still holds an open own_wip CONFLICT (measured: guarded-inline-2 ended with
# one on U-011's own test file) BEFORE the run evidence commit (--rebind-wip; --retire repeats it as a backstop, never under
# --dry-run), and never closes over a CONFLICT that re-bind leaves — the ledger keeps it named until a human decides it
M15="$T/m15"; MK "$M15"; mkunit "$(MV "$M15")" U-002 "Beta page" docs/beta.md "depends_on: []" '
## Claims
- C-U002-01 "the config module exists" — expect: lib/config.js — must-exist'
seed "$M15"; rb "$M15" U-002; P15="$(J "$(depat "$M15")" 'd["plan"]')"
sleep 1; printf '<!-- Generated by mega-sdd execute-bolts 9.0.0\n     Unit: U-002 · provenance: x -->\n# beta (wip)\n' > "$M15/docs/beta.md"; rb "$M15" U-002
sleep 1; bolt "$M15" U-002 docs/beta.md "Beta page"; report "$(MV "$M15")" U-002 "$M15" docs/beta.md; cpx "$M15" "$T/m15x"; cpx "$M15" "$T/m15d"
open15() { JF "$(MV "$1")/bolts/U-002/binding.json" 'sorted((c["id"], bool(c.get("own_wip"))) for c in d["claims"] if c["verdict"] == "CONFLICT" and not c.get("resolution"))'; }
cl15() { OUT="$(bash "$DEP" --cwd="$1" --vault="$(MV "$1")" "${@:2}" 2>"$T/dep.err")"; R=$?; }
[ "$(open15 "$M15")" = "[('C-U002-A01', True)]" ] && [ -f "$P15" ] && ok "m11a: a resume's own_wip CONFLICT is still open after the unit is done (no later re-bind)" || bad "m11a: $(open15 "$M15") plan=$P15"
cl15 "$M15" --rebind-wip
[ $R -eq 0 ] && [ "$(J "$OUT" 'd.get("rebound")')" = "['U-002']" ] && [ "$(open15 "$M15")" = "[]" ] && [ -f "$P15" ] && [ "$(scanat "$M15")" = 0 ] \
  && ok "m11b: --rebind-wip (the close step before the run evidence commit) re-binds it: rebound [U-002], CONFIRMED, the plan stays open, no bypass" || bad "m11b: rc=$R $OUT $(open15 "$M15") $(head -c 200 "$T/dep.err")"
cl15 "$M15" --retire
[ $R -eq 0 ] && [ "$(J "$OUT" '(d.get("rebound"), len(d["retired"]))')" = "([], 2)" ] && [ ! -e "$P15" ] && ok "m11c: --retire then has nothing left to re-bind and retires the run" || bad "m11c: rc=$R $OUT"
cl15 "$T/m15d" --retire --dry-run
[ $R -eq 0 ] && [ "$(J "$OUT" 'd.get("rebound")')" = "[]" ] && [ "$(open15 "$T/m15d")" = "[('C-U002-A01', True)]" ] && [ ! -e "$(MV "$T/m15d")/bolts/$(basename "$P15")" ] \
  && ok "m11d: --retire --dry-run retires the plan and re-binds nothing (a dry run writes no binding)" || bad "m11d: rc=$R $OUT $(open15 "$T/m15d")"
cl15 "$T/m15d" --retire; [ $R -eq 0 ] && [ "$(J "$OUT" 'd.get("rebound")')" = "['U-002']" ] && [ "$(open15 "$T/m15d")" = "[]" ] \
  && ok "m11e: with no open plan (a skipped close step) --retire still re-binds it — the backstop" || bad "m11e: rc=$R $OUT"
sleep 1; G "$T/m15x" rm -q lib/config.js && G "$T/m15x" commit -qm "chore: drop the config module"; L15="$(MV "$T/m15x")/bolts/$(basename "$P15" | sed 's/_exec-plan-/_inline-ledger-/')"
cl15 "$T/m15x" --rebind-wip
[ $R -eq 1 ] && [ "$(J "$OUT" '(d["halt"]["type"], d["halt"]["scope"], d["halt"]["units"], d["rebound"])')" = "('binding_conflict', 'close', {'U-002': ['C-U002-01']}, ['U-002'])" ] \
  && J "$OUT" 'd["halt"]["keterangan"]' | grep -q . && grep -qx 'Close: halt binding_conflict U-002' "$L15" \
  && ok "m11f: a CONFLICT the re-bind leaves (not own_wip) → exit 1 naming it (scope close), recorded in the run ledger" || bad "m11f: rc=$R $OUT $(cat "$L15" 2>&1 | tail -2)"
cl15 "$T/m15x" --rebind-wip; R1=$R; cl15 "$T/m15x" --retire
[ $R1 -eq 1 ] && [ $R -eq 1 ] && [ "$(J "$OUT" '(d["halt"]["units"], d["retired"])')" = "({'U-002': ['C-U002-01']}, [])" ] && [ -f "$(MV "$T/m15x")/bolts/$(basename "$P15")" ] \
  && ok "m11g: a re-run (a compaction) and --retire still stop on it — the ledger line, not the gone own_wip flag, names it; nothing retired" || bad "m11g: rc=$R1/$R $OUT"
bash "$S/write-unit-binding.sh" --cwd="$T/m15x" --vault="$(MV "$T/m15x")" --unit=U-002 --resolve=C-U002-01=KEEP_CODE --by=user >/dev/null 2>&1; cl15 "$T/m15x" --retire
[ $R -eq 0 ] && [ ! -e "$(MV "$T/m15x")/bolts/$(basename "$P15")" ] && ok "m11h: once a human decides it (resolve-oq --binding), the close goes on and retires" || bad "m11h: rc=$R $OUT"

# m9: a literal inline run — create → modify, evidence committed, a fresh clone passes the gate
M13="$T/m13"; MK "$M13"; V13="$(MV "$M13")"
mkunit "$V13" U-001 "Greeting function" src/greet.js "depends_on: []"; mkunit "$V13" U-002 "Shout option" src/greet.js "depends_on: [U-001]" "" modify modify
seed "$M13"; rb "$M13" U-001,U-002; P13="$(J "$(depat "$M13")" 'd["plan"]')"
blk() { brief "$1" "$2" | awk -v k="$3" '/^```bash$/ { n++; if (n == k) { f = 1; next } } /^```$/ { if (f) exit } f'; }
hdr() { brief "$1" "$2" | awk '/^```$/ { if (f) exit; f = 1; next } f'; }
runblk() { ( cd "$1" && GIT_AUTHOR_NAME=t GIT_AUTHOR_EMAIL=t@t GIT_COMMITTER_NAME=t GIT_COMMITTER_EMAIL=t@t bash -c "$2" >/dev/null 2>&1 ); }
if [ -f "$P13" ]; then
  printf '%s' "$(hdr "$P13" 1)" | grep -qF "provenance: .mega-sdd/vaults/demo/units/U-001.md" && ok "m9a: the provenance header points at the tracked unit file" || bad "m9a: $(hdr "$P13" 1)"
  for n in 1 2; do
    u="U-00$n"; rb "$M13" "$u"; mkdir -p "$M13/src"
    if [ $n = 1 ]; then { hdr "$P13" 1 | sed 's|^|// |'; printf 'module.exports = function greet(n) { return "hi " + n; };\n'; } > "$M13/src/greet.js"; else printf '// shout option\n' >> "$M13/src/greet.js"; fi
    runblk "$M13" "$(blk "$P13" $n 1)"; evid "$M13" "$u"; report "$V13" "$u" "$M13" src/greet.js; runblk "$M13" "$(blk "$P13" $n 2)"
  done
  [ "$(git -C "$M13" log --format=%s | grep -c 'chore(sdd): evidence')" = 2 ] && [ -z "$(git -C "$M13" status --porcelain -- "$V13/bolts/U-001" "$V13/bolts/U-002")" ] \
    && ok "m9c: after the two tasks every unit's evidence is committed" || bad "m9c: $(git -C "$M13" log --format=%s | head -6 | tr '\n' '|')"
  [ "$(J "$(depat "$M13" --pending)" 'd["pending"]')" = "[]" ] && ok "m9d: the creating unit is not re-planned after its dependent modified the file (done rule)" || bad "m9d: $(depat "$M13" --pending)"
  rm -rf "$T/m13c"; git clone -q "$M13" "$T/m13c" 2>/dev/null
  [ "$(scanat "$T/m13c")" = 0 ] && ok "m9e: a fresh clone passes the conflict-bypass gate (the evidence travels with the code)" || bad "m9e: $(reasons "$T/m13c")"
  printf '// wip\n' >> "$M13/src/greet.js"
  [ "$(J "$(depat "$M13" --pending)" 'd["pending"]')" = "['U-001', 'U-002']" ] && ok "m9f: an uncommitted edit of a target keeps its units pending" || bad "m9f: $(depat "$M13" --pending)"
  G "$M13" checkout -q -- src/greet.js; sleep 1; printf '// hand edit\n' >> "$M13/src/greet.js"; G "$M13" commit -qam "chore: hand edit"
  [ "$(J "$(depat "$M13" --pending)" 'd["pending"]')" = "['U-001', 'U-002']" ] && ok "m9g: a commit no unit owns still makes both units stale (sync semantics kept)" || bad "m9g: $(depat "$M13" --pending)"
else
  bad "m9: no plan for the create→modify fixture"
fi

# ── h: wiring + docs ─────────────────────────────────────────────────────────
RETIRED='--agents is retired: the per-unit agent path was removed (spec v9 §8.6); running the default inline run.'
SK="$P/skills/execute-bolts/SKILL.md"; IR="$P/skills/execute-bolts/references/inline-run.md"; SPEC="$ROOT/docs/superpowers/specs/2026-09-27-v9-simplification-design.md"
grep -E -- '--orphan-scan --batch-suite-gate' "$P/hooks/stop" | grep -q -- '--conflict-bypass-scan' && grep -E 'validate-bolt-artifacts\.sh.*--orphan-scan' "$P/hooks/pre-tool-use" | grep -q -- '--conflict-bypass-scan' \
  && ok "h1: the Stop hook and the execute-bolts gate compose --conflict-bypass-scan" || bad "h1: not wired"
python3 - "$P/hooks/pre-tool-use" <<'PY' && ok "h2: every protected list names the bypass state; no run record anywhere in the hook" || bad "h2: a protected list lacks it"
import re, sys
t = open(sys.argv[1]).read()
lists = re.findall(r'prot = re\.compile\(r"(.*)"\)', t) + re.findall(r"PROTECTED='(.*)'", t)
guarded = re.findall(r"_GUARDED = \((.*?)\n[ \t]*\)", t, re.S)
assert len(lists) == 3 and len(guarded) == 2, (len(lists), len(guarded))
assert all(r"\.bolt-conflict-bypass-state\.json|" in s for s in lists) and all('".bolt-conflict-bypass-state.json"' in g for g in guarded)
assert "_run.json" not in t and "PROTECTED_DIR" not in t
PY
grep -q -- '--inline' "$SK" && grep -qF 'references/inline-run.md' "$SK" && [ "$(wc -l < "$SK")" -le 500 ] && grep -qE 'Announce at start.*`mega-sdd-trace:execute-bolts`' "$SK" \
  && grep -E '^3\.9\. ' "$SK" | grep -qF 'runs on every run' && ! grep -E '^3\.9\. ' "$SK" | grep -qF -- '--agents' && grep -E '^  - `--agents` — retired' "$SK" | grep -qF -- "$RETIRED" \
  && grep -qE '^  - `--inline` — accepted no-op alias of the default' "$SK" && ! grep -E '^  - `--inline`' "$SK" | grep -q 'usage error' \
  && ok "h3: SKILL.md: inline (pointer), --agents retired in one line (3.9 runs on every run), --inline a no-op alias, <= 500 lines, the announce tag kept" || bad "h3: SKILL.md wiring"
[ -f "$IR" ] && [ "$(wc -l < "$IR")" -le 130 ] && grep -qE '^[[:space:]]*mega-sdd-trace:execute-bolts[[:space:]]*$' "$IR" && ok "h4: inline-run.md <= 130 lines, the review template's trace line on its own line" || bad "h4: inline-run.md $(wc -l < "$IR" 2>/dev/null) lines"
for s in 'derive-exec-plan.sh --cwd=<root> --vault=<vault> --pending' 'rebind-units.sh' '--conflict-bypass-scan' 'delivery-check.sh' '_inline-ledger' 'superpowers:executing-plans' \
         'resolve-oq --binding' 'run-full-suite.sh --cwd=<root> --base=<run_base>' 'comma-join' 'hard_rule_violated' 'l0-results' 'acceptance_expects_missing' \
         'write-unit-quarantine.sh' '`--dry-run`' '`--force`' '`--no-full-suite`' 'Resume' 'chore(sdd): evidence' 'empty commit range' 'Threat model' 'evasion' \
         '--retire' 'own_wip' 'rebind_skipped' '--rebind-wip' 'Close: reviewed' '--max-retries' 'detect-drift'; do
  grep -qF -- "$s" "$IR" && ok "h5: inline-run.md names: $s" || bad "h5: inline-run.md lacks: $s"
done
H5B="$T/h5b"; cp -R "$F" "$H5B"   # a copy: the gate writes state files, F stays as it is
bash "$VBA" --cwd="$H5B" --orphan-scan --batch-suite-gate --postflight-scan --recompute --whitelist-scan --acceptance-scan --panel-scan --conflict-bypass-scan >/dev/null 2>&1; [ $? -ne 2 ] \
  && ok "h5b: a plan written before --panel-scan left its callers still passes its gate (the no-op arm; drop this with the arm)" || bad "h5b: the legacy gate with --panel-scan exits 2 (unknown arg)"
ld="$(grep -n 'delivery-check.sh' "$IR" | tail -1 | cut -d: -f1)"; lg="$(grep -n -- '--conflict-bypass-scan' "$IR" | tail -1 | cut -d: -f1)"
[ -n "$ld" ] && [ -n "$lg" ] && [ "$ld" -lt "$lg" ] && ok "h6: delivery-check runs before the run-boundary gate" || bad "h6: delivery-check $ld, gate $lg"
grep -q -- '--inline' <(sed -n 's/^argument-hint: //p' "$P/commands/mega-sdd.md") && grep -q 'execute-bolts --all --lite --inline' "$P/commands/mega-sdd.md" \
  && grep -q -- '--inline' "$P/skills/orchestrate-flow/SKILL.md" && [ "$(sed -n 's/^version: //p' "$P/skills/orchestrate-flow/SKILL.md")" != "3.1.0" ] \
  && ! grep -qE -- '--agents|--no-escalate|<tier>\|' <(sed -n 's/^argument-hint: //p' "$P/commands/mega-sdd.md") && ! grep -q 'execute-bolts --all --lite --agents' "$P/commands/mega-sdd.md" "$P/skills/orchestrate-flow/SKILL.md" \
  && grep -qF -- "$RETIRED" "$P/commands/mega-sdd.md" && grep -qF -- "$RETIRED" "$P/skills/orchestrate-flow/SKILL.md" \
  && ok "h7: the front door and orchestrate-flow retire --agents in one line and forward the --inline alias (version bumped)" || bad "h7: --agents retirement / --inline forwarding"
grep -F '**Step 0 — pick the lane FIRST' "$P/commands/mega-sdd.md" | grep -qF -- '`--inline`, `--agents`) imply `--guarded`' && grep -qF -- '`--agents` imply guarded' "$P/references/direct-lane.md" \
  && grep -F -- '`--model-tier=<role>:<tier>`' "$P/commands/mega-sdd.md" | grep -qF -- '--model-tier=<tier> and --no-escalate are retired (no implementer is dispatched); --model-tier=<role>:<tier> still sets extract-intelligence tiers.' \
  && ok "h7b: Step 0 routes --agents to guarded (front door + direct-lane); --model-tier=<role>:<tier> kept, bare <tier>/--no-escalate retired in one line" || bad "h7b: --agents lane / --model-tier scope"
grep -qE 'guarded-inline\)[[:space:]]*KIND=megasdd; FLAGS="--guarded --inline"' "$ROOT/benchmarks/scripts/vanilla-ab-batch.sh" \
  && ! grep -q 'guarded-agents' "$ROOT/benchmarks/scripts/vanilla-ab-batch.sh" && ok "h8: the guarded-inline alias arm; no guarded-agents arm" || bad "h8: arms"
python3 - "$P/CLAUDE.md" "$SPEC" "$IR" <<'PYH' && ok "h9: CLAUDE.md (invariant #2 dated exception), spec §8.2 and inline-run (e) state the threat model" || bad "h9: contract/threat-model wording"
import re, sys
t, spec, ir = (open(p).read() for p in sys.argv[1:4])
inv2 = re.search(r"\n2\. \*\*The CONFLICT gate blocks\*\*(.*?)\n3\. ", t, re.S).group(1)
assert "conflict_bypassed" in inv2 and "--inline" in inv2 and "§8.4" in inv2 and "2026-09-27" in inv2 and "evasion" in inv2, "inv2"
assert "derive-exec-plan.sh" in inv2 and "By default" in inv2 and "§8.6" in inv2 and "Under `--agents`" not in inv2, "inv2 default, per-dispatch path removed (§8.6)"
assert "§8.6" in re.search(r"## What we will not accept(.*?)\n## ", t, re.S).group(1), "wna"
assert "### 8.5 Outcome" in spec and "2026-09-28-p2-inline-results.md" in spec.split("### 8.5 Outcome")[1], "spec 8.5"
s82 = re.search(r"### 8\.2(.*?)### 8\.3", spec, re.S).group(1)
assert "Threat model" in s82 and "evasion" in s82 and "out of scope" in s82, "spec"
assert "_run.json" not in t + spec + ir and "bound_since" not in t + spec + ir, "a deleted leg is still documented"
PYH
! grep -rqE '_run\.json|bound_since|unattributed_commit|patch-id' "$P/scripts" "$P/hooks" "$P/skills" && ok "h10: no deleted leg survives in scripts, hooks or skills" || bad "h10: $(grep -rlE '_run\.json|bound_since|unattributed_commit|patch-id' "$P/scripts" "$P/hooks" "$P/skills")"
grep -qF 'The default path is unchanged by P2' "$ROOT/benchmarks/runbooks/p2-inline-vs-agents.md" && bad "h11: the runbook claims an unchanged default path" || ok "h11: the runbook does not claim an unchanged default path"
! grep -qE 'the seven execute-bolts artifact gates|ALL SEVEN bolt-stage' "$P/CLAUDE.md" && ! grep -q 'all six scans' "$ROOT/tests/token-efficiency/test-4abc-spawn-tax.sh" \
  && ok "h12: gate counts match the implementation" || bad "h12: count drift"
grep -qF -- '--inline' "$ROOT/tests/skill-triggering/execute-bolts.test.md" && grep -F 'execute-bolts --inline' "$ROOT/docs/gateway-contract.md" | grep -qF 'mega-sdd-trace:execute-bolts' \
  && ok "h13: the trigger fixtures and the gateway contract carry the inline reviewer" || bad "h13: trigger/gateway"
! grep -qE '^vault_source:' "$0" && ok "h14: the fixtures use context_source (layout 3)" || bad "h14: vault_source in the fixture"
python3 - "$ROOT" <<'PYD' && ok "h15: no surface a default run or a new session reads presents the per-dispatch path as the default" || bad "h15: a surface still presents the per-dispatch path as the default"
import re, sys
R = sys.argv[1]; P = R + "/plugins/mega-sdd"
rd = lambda f: open(f, encoding="utf-8").read()
core = rd(P + "/skills/using-mega-sdd/SKILL.md").split("ANCHOR-CORE ends")[0]
hg = [l for l in core.splitlines() if l.startswith("**Hard gate:**")][0]
assert "run start" in hg and "--agents" not in hg and "binding_conflict" in hg and "resolve-oq --binding" in hg, "anchor hard gate"
assert "| execute-bolts pre-flight 3.9 (" not in rd(P + "/skills/using-mega-sdd/SKILL.md"), "anchor table row"
cl = rd(P + "/skills/orchestrate-flow/references/convergence-loops.md")
assert "`scope: close`" in cl and "Close: reviewed" in cl and "--agents" not in cl, "convergence rows"
fd = rd(P + "/commands/mega-sdd.md")
assert "quarantined and reported" in fd, "front door --deep binding_conflict"
eb = rd(P + "/skills/execute-bolts/SKILL.md")
mr = [l for l in eb.splitlines() if l.startswith("  - `--max-retries=N`")][0]
assert "prose" in mr and "resolve-review-tier" not in mr, "--max-retries scope"
for f in ("--parallel", "--per-squad"):
    assert "(`--agents` only)" in [l for l in eb.splitlines() if l.startswith("  - `%s`" % f)][0], f
assert "(every run)" not in eb and "every run —" not in rd(P + "/skills/execute-bolts/references/jit-bind-and-quarantine.md")[:400], "3.9 every run"
cond = eb.split("**Only when the condition holds")[1]
assert "review-panel.md" not in eb and cond, "review-panel.md retired (P3 C3)"
br = rd(P + "/skills/execute-bolts/references/superpowers-bridge.md")
assert "the ONLY dispatch path" not in br and "(default)" not in br.split("## Dispatch order")[1][:200] and "`--agents`" in br[:600], "bridge scope"
assert "`--max-retries" in rd(P + "/skills/execute-bolts/references/inline-run.md").split("## (b)")[0], "inline-run flag table"
assert "(JIT bind per unit, CONFLICT gate at dispatch)" not in rd(R + "/CLAUDE.md") and "`--agents` keeps" not in rd(R + "/CLAUDE.md"), "root CLAUDE.md"
rm = rd(R + "/README.md")
assert "`--agents`" in [l for l in rm.splitlines() if "Removed in P3" in l][0] and "Before a unit is dispatched it is bound" not in rm, "root README"
ct = rd(R + "/CONTRIBUTING.md")
assert "quarantined at run start" in ct and "--agents" not in ct, "CONTRIBUTING rail 2"
sp = rd(R + "/docs/superpowers/specs/2026-09-27-v9-simplification-design.md")
assert "no flag = today's per-unit path" not in sp and re.search(r"A normal `--agents` run never trips\s+it", sp) and re.search(r"### 8\.1 .*\(adopted, §8\.5\)", sp), "spec"
assert "--rebind-wip" in sp.split("### 8.5 Outcome")[1], "spec 8.5 residual fix"
PYD

echo; [ $rc -eq 0 ] && echo "ALL PASS" || echo "FAILURES PRESENT"; exit $rc
