#!/usr/bin/env bash
# build-project-index.sh — project-level manifest of every vault (multi-PRD
# lifecycle, spec 2026-06-12-multi-prd-lifecycle-design.md).
#
# A project that grows PRD-by-PRD (PRD 1 ships, PRD 2 adds an epic, …) needs ONE
# place that lists every vault, its source doc, status, and the feature area it
# owns — so PRD N knows what PRD 1..N-1 shipped and the new-vault-vs-diff
# decision is unambiguous. Scans .mega-sdd/vaults/*/ and writes
# .mega-sdd/project.md (derived — regenerated, never hand-edited).
#
# Usage: build-project-index.sh --cwd=<project-root>
# Exit 0 always (a missing/empty project is a valid empty index).

set -uo pipefail
CWD=""
for arg in "$@"; do
  case "$arg" in --cwd=*) CWD="${arg#--cwd=}" ;; esac
done
[ -n "$CWD" ] && [ -d "$CWD/.mega-sdd" ] || exit 0

CWD="$CWD" python3 <<'PYEOF' 2>/dev/null || true
import glob, json, os, re
from datetime import datetime, timezone

cwd = os.environ["CWD"]
vroot = os.path.join(cwd, ".mega-sdd", "vaults")
rows = []
for vdir in sorted(glob.glob(os.path.join(vroot, "*"))):
    if not os.path.isdir(vdir) or os.path.basename(vdir).startswith((".", "_")):
        continue
    slug = os.path.basename(vdir)
    vj = os.path.join(vdir, "vault.json")
    title, source, vault_version, scope = slug, "?", "?", ""
    if os.path.isfile(vj):
        try:
            d = json.load(open(vj))
            title = d.get("title") or d.get("vault_title") or title
            source = d.get("source_prd") or d.get("source") or d.get("prd_path") or source
            vault_version = str(d.get("vault_version") or d.get("version") or vault_version)
            scope = d.get("scope") or ""
        except Exception:
            pass
    units = glob.glob(os.path.join(vdir, "units", "U-*.md"))
    bolts = glob.glob(os.path.join(vdir, "bolts", "U-*", "bolt-report.md"))
    has_binding = os.path.isfile(os.path.join(vdir, "binding.md"))
    # status from artifact presence
    if not units:
        status = "intent" if os.path.isfile(os.path.join(vdir, "00-index.md")) else "empty"
    elif not bolts:
        status = "units-ready"
    elif len(bolts) < len(units):
        status = "in-progress (%d/%d bolts)" % (len(bolts), len(units))
    else:
        status = "shipped"
    # one-line feature area from 01-overview Product line (best-effort)
    area = ""
    ov = os.path.join(vdir, "01-overview.md")
    if os.path.isfile(ov):
        try:
            txt = open(ov, encoding="utf-8", errors="replace").read()
            m = re.search(r"^## Product\s*\n+(.+)", txt, re.M)
            if m:
                area = re.sub(r"\(.*?\)", "", m.group(1)).strip()[:90]
        except OSError:
            pass
    rows.append({"slug": slug, "title": title, "source": source, "version": vault_version,
                 "scope": scope, "status": status, "units": len(units), "bolts": len(bolts), "area": area})

ts = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
out = ["---", "type: project-index", "generated_by: build-project-index.sh",
       "generated_at: %s" % ts, "vault_count: %d" % len(rows), "---", "",
       "# Project Index", "",
       "> DERIVED — regenerated by `build-project-index.sh`; do not hand-edit. One row per vault.",
       "> The sequence of vaults IS the project's PRD/epic history. A new doc → new vault (new epic)",
       "> or diff-vault (revision of an existing source) per `references/multi-prd-lifecycle.md`.", ""]
if not rows:
    out += ["_No vaults yet._", ""]
else:
    out += ["| Vault | Title | Source | Ver | Status | Units | Bolts | Area |",
            "|---|---|---|---|---|---|---|---|"]
    for r in rows:
        out.append("| `%s` | %s | %s | %s | %s | %d | %d | %s |" % (
            r["slug"], r["title"], r["source"], r["version"], r["status"], r["units"], r["bolts"], r["area"]))
    out.append("")
    shipped = [r["slug"] for r in rows if r["status"] == "shipped"]
    active = [r["slug"] for r in rows if r["status"] not in ("shipped", "empty")]
    out += ["## Lifecycle", "",
            "- **Shipped vaults** (their features are now codebase reality — bind new vaults against them): %s" % (", ".join("`%s`" % s for s in shipped) or "none"),
            "- **Active vaults** (in flight): %s" % (", ".join("`%s`" % s for s in active) or "none"),
            "- **Project constitution**: `.mega-sdd/constitution.md` (project-scope locked rules every vault inherits — a new vault MUST NOT contradict it).", ""]

path = os.path.join(cwd, ".mega-sdd", "project.md")
tmp = path + ".tmp"
with open(tmp, "w", encoding="utf-8") as f:
    f.write("\n".join(out))
os.replace(tmp, path)
PYEOF
exit 0
