#!/usr/bin/env bash
# emit-claude-rules.sh — A6 (spec 2026-08-17-constitution-claude-rules.md).
# Emits path-scoped .claude/rules/ files from <vault>/constitution.md, with
# paths GROUNDED in the FRONTMATTER target_files of units whose Hard rules
# cite each clause — zero glob inference, uncited clauses SKIPPED and listed.
# Dry-run by default; --write applies; refresh deletes ONLY files matching
# this vault's exact generated pattern mega-sdd-<slug>-<ID>.md.
# Round-hardened (B-1/M-1..M-4): frontmatter-only path harvest, §-section-scoped
# clause parse (first occurrence wins, fences skipped), left-bounded citation
# match, slug-exact stale pattern, single-quoted YAML path escaping.
# Exit: 0 ok · 2 usage/missing inputs.
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

VAULT=""; CWD=""; WRITE=0
for arg in "$@"; do
  case "$arg" in
    --vault=*) VAULT="${arg#*=}" ;;
    --cwd=*)   CWD="${arg#*=}" ;;
    --write)   WRITE=1 ;;
    *) echo "usage: emit-claude-rules.sh --vault=<dir> --cwd=<root> [--write]" >&2; exit 2 ;;
  esac
done
[ -n "$VAULT" ] && [ -d "$VAULT" ] || { echo "usage: --vault=<existing vault dir> required" >&2; exit 2; }
[ -n "$CWD" ] && [ -d "$CWD" ] || { echo "usage: --cwd=<project root> required" >&2; exit 2; }
[ -f "$VAULT/constitution.md" ] || { echo "no constitution.md in vault — nothing to emit" >&2; exit 2; }

VAULT="$VAULT" CWD="$CWD" WRITE="$WRITE" python3 <<'PYEOF'
import os, re, glob, json, hashlib

vault = os.environ["VAULT"]; cwd = os.environ["CWD"]; write = os.environ["WRITE"] == "1"
slug = os.path.basename(os.path.normpath(vault))
const_path = os.path.join(vault, "constitution.md")
const = open(const_path, encoding="utf-8").read()
const_sha = hashlib.sha256(const.encode()).hexdigest()
ver_m = re.search(r'^\*\*Version\*\*:\s*(.+)$', const, re.M)
const_ver = ver_m.group(1).strip() if ver_m else "unknown"

# ── clauses: ONLY under "## §<letter>" headings, outside code fences, first
# occurrence wins (M-1: a revision-history or prose "- B-001: …" line must
# never mint or overwrite a clause).
clauses = {}
in_section = False
in_fence = False
for ln in const.split("\n"):
    if ln.strip().startswith("```"):
        in_fence = not in_fence
        continue
    if in_fence:
        continue
    h = re.match(r'^## (.*)$', ln)
    if h:
        in_section = h.group(1).lstrip().startswith("§")
        continue
    if not in_section:
        continue
    m = re.match(r'^- (?:§)?([A-F]-\d+):\s*(.+)$', ln)
    if m and m.group(1) not in clauses:
        clauses[m.group(1)] = ln

# ── units: target_files from the FRONTMATTER ONLY (B-1) + Hard-rules citations
# with a LEFT boundary so SUB-001 never cites B-001 (M-2).
def frontmatter(t):
    m = re.match(r'^---\n(.*?)\n---\n', t, re.S)
    return m.group(1) if m else ""

def tf_paths(fm):
    # target_files block: "- path: <value>" rows; value = rest of line, minus
    # trailing comment-free whitespace; surrounding quotes stripped (M-4).
    out = []
    in_tf = False
    for ln in fm.split("\n"):
        if re.match(r'^target_files:\s*$', ln):
            in_tf = True
            continue
        if in_tf:
            if re.match(r'^\S', ln):          # next top-level key ends the block
                in_tf = False
                continue
            m = re.match(r'^\s*-\s*path:\s*(.+?)\s*$', ln)
            if m:
                v = m.group(1)
                if len(v) >= 2 and v[0] == v[-1] and v[0] in "'\"":
                    v = v[1:-1]
                if v:
                    out.append(v)
    return out

cite_paths = {}
pathless_cited = set()
for up in sorted(glob.glob(os.path.join(vault, "units", "U-*.md"))):
    t = open(up, encoding="utf-8").read()
    fm = frontmatter(t)
    paths = tf_paths(fm)
    hr = re.search(r'^## Hard rules\n(.*?)(?=^## |\Z)', t, re.M | re.S)
    if not hr:
        continue
    body = hr.group(1)
    for cid in clauses:
        if re.search(r'(?<![\w-])(?:§)?' + re.escape(cid) + r'\b', body):
            if paths:
                cite_paths.setdefault(cid, set()).update(paths)
            else:
                pathless_cited.add(cid)

def yq(p):
    # single-quoted YAML scalar: the ONLY escape is '' — closes M-4's quote/
    # backslash corruption classes (paths are line-captured, no newlines).
    return "'" + p.replace("'", "''") + "'"

emitted, skipped = [], []
files = {}
for cid, line in sorted(clauses.items()):
    ps = sorted(cite_paths.get(cid, ()))
    if not ps:
        skipped.append(cid)
        continue
    fname = f"mega-sdd-{slug}-{cid}.md"
    body = "---\n" \
        + "paths:\n" + "".join(f'  - {yq(p)}\n' for p in ps) \
        + "---\n\n" \
        + f"# Constitution {cid} ({slug})\n\n" \
        + line + "\n\n" \
        + f"> GENERATED by mega-sdd from `{os.path.relpath(const_path, cwd)}` " \
        + f"(constitution version {const_ver}, sha256 {const_sha[:12]}…) — do not hand-edit; " \
        + "paths are the frontmatter target_files of the units whose Hard rules cite this clause; " \
        + "refresh via /mega-sdd:sync.\n"
    files[fname] = body
    emitted.append(cid)

rules_dir = os.path.join(cwd, ".claude", "rules")
# M-3: slug-EXACT generated pattern — vault `pay` can never delete `pay-v2`'s
# files, and a hand-written mega-sdd-<slug>-custom.md is NOT deletable either.
gen_pat = re.compile(r'^mega-sdd-' + re.escape(slug) + r'-[A-F]-\d+\.md$')
stale = []
if os.path.isdir(rules_dir):
    for f in sorted(os.listdir(rules_dir)):
        if gen_pat.match(f) and f not in files:
            stale.append(f)

plan = {"vault": slug, "constitution_sha256": const_sha, "emitted": emitted,
        "skipped_ungrounded": sorted(set(skipped) | pathless_cited),
        "stale_removed": stale, "written": bool(write)}

if write:
    os.makedirs(rules_dir, exist_ok=True)
    for fname, body in files.items():
        tmp = os.path.join(rules_dir, fname + ".tmp")
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(body)
        os.replace(tmp, os.path.join(rules_dir, fname))
    for f in stale:
        os.remove(os.path.join(rules_dir, f))

print(json.dumps(plan, indent=0).replace("\n", " "))
PYEOF
