#!/usr/bin/env bash
# migrate-vault-layout3.sh — the `migrate-paths --vault-layout=3` rung (v8 P3, spec
# 2026-09-10 §7 P3 + owner amendment): ONE layout-2 vault (vault.md / model.md / flows.md /
# constraints.md) → layout-3 (`context.md`, the plan-born shape every v8 consumer reads via
# `vault_md.resolve_doc` 3 → 2 → legacy).
#
#   migrate-vault-layout3.sh --vault=<vault-dir> [--apply] [--cwd=<root>]
#
# DRY-RUN BY DEFAULT (--apply executes). Concat is VERBATIM relocation, same doctrine as
# the layout-2 rung: nothing is rewritten to look fresher than it is.
#   * context.md frontmatter = vault.md's lock scalars (+ `vault_layout: 3`, type/doc_id
#     `context`); H1 kept; sections land under the layout-3 H2 contract
#     (`_lib/vault_md.V3_REQUIRED_HEADERS` / V3_SECTION_CODES): ## Overview (opt) ·
#     ## Architecture (kept — AR is a recognised layout-3 code, so drift's Architecture
#     compare survives a MIGRATED vault) · ## Flows (flows.md) · ## Data model (model.md) ·
#     ## Constraints (constraints.md minus its OQ section) · ## Open Questions (the ONE OQ
#     home) · ## Decisions (opt).
#   * dead sections (00-index residue: Glossary / Source documents / Auto-Classification
#     Review / Changelog) + the four layout-2 docs + binding.md / binding.json /
#     claims-ledger.json move VERBATIM to `<vault>/_meta/archive/layout2/` (git mv when
#     tracked) — nothing is deleted.
#   * binding.md is SPLIT per unit: every claim a unit cites in `binding_refs` (C-ids,
#     CONFLICT-ids, OQ-ids) lands in `bolts/U-XXX/binding-migrated.json` with its verdict,
#     state, anchor and any human RESOLUTION — the human-decision surface is preserved.
#     It is NOT `bolts/U-XXX/binding.json`: that file has ONE writer (write-unit-binding.sh,
#     hook-guarded evidence) and is regenerated by the mandatory full JIT re-bind below
#     (regenerate, jangan fabricate — line anchors are never patched to fake freshness).
#   * unit `vault_source` / `context_source` doc names (vault.md / model.md / flows.md /
#     constraints.md → context.md) are rewritten NAME-only (anchors untouched); VAULT-DIFF too.
#   * after apply: derive-vault-json.sh regenerates vault.json (layout-3 aware) and the
#     mandatory "full JIT re-bind required" step is printed.
# Idempotent: context.md present → no-op exit 0. Legacy 7-file vault → exit 2 (run the
# layout-2 rung first). Dirty git tree under --apply → exit 2 (preview stays available).
set -u
VAULT=""; APPLY=0; CWD="."
for arg in "$@"; do case "$arg" in
  --vault=*) VAULT="${arg#*=}" ;; --apply) APPLY=1 ;; --cwd=*) CWD="${arg#*=}" ;;
  *) echo "usage: migrate-vault-layout3.sh --vault=<dir> [--apply] [--cwd=<root>]" >&2; exit 2 ;;
esac; done
[ -n "$VAULT" ] && [ -d "$VAULT" ] || { echo "migrate-vault-layout3: --vault=<dir> required" >&2; exit 2; }
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$VAULT/context.md" ]; then echo "migrate-vault-layout3: $VAULT is already layout-3 (context.md exists) — no-op."; exit 0; fi
if [ ! -f "$VAULT/vault.md" ]; then
  if [ -f "$VAULT/00-index.md" ]; then echo "migrate-vault-layout3: $VAULT is a legacy 7-file vault — run migrate-paths.sh --vault-layout=$VAULT --apply (layout-2) first" >&2; exit 2; fi
  echo "migrate-vault-layout3: $VAULT has no vault.md — not a layout-2 vault" >&2; exit 2
fi
if [ "$APPLY" -eq 1 ] && git -C "$CWD" rev-parse --is-inside-work-tree >/dev/null 2>&1 \
   && [ -n "$(git -C "$CWD" status --porcelain 2>/dev/null | grep -v '^??')" ]; then
  echo "migrate-vault-layout3: REFUSED — git tree has uncommitted changes. Commit/stash first (preview stays available without --apply)." >&2
  exit 2
fi
echo "== vault-layout=3: $VAULT $([ "$APPLY" -eq 1 ] && echo '(APPLY)' || echo '(dry-run — add --apply to execute)')"
RC=0
MEGA_SDD_LIB_DIR="${SCRIPT_DIR}/_lib" V_VAULT="$VAULT" V_APPLY="$APPLY" V_CWD="$CWD" python3 <<'PYEOF' || RC=$?
import glob, json, os, re, subprocess, sys
sys.path.insert(0, os.environ["MEGA_SDD_LIB_DIR"])
import vault_md
vault = os.environ["V_VAULT"]; apply_ = os.environ["V_APPLY"] == "1"; cwd = os.environ["V_CWD"]

def rd(name):
    p = os.path.join(vault, name)
    return open(p, encoding="utf-8", errors="surrogateescape").read() if os.path.isfile(p) else None

H2_RE = re.compile(r"(?m)^##\s+(.+?)\s*$")
def sections(md):
    heads = [(m.group(1), m.start()) for m in H2_RE.finditer(md)]
    return [(h, s, heads[i + 1][1] if i + 1 < len(heads) else len(md)) for i, (h, s) in enumerate(heads)]
def cut_section(md, name):
    for h, s, e in sections(md):
        if h.lower().startswith(name.lower()):
            body = md[s:e]; body = body.split("\n", 1)[1] if "\n" in body else ""
            return body.strip("\n"), (md[:s] + md[e:])
    return None, md
def strip_fm(md):
    m = re.match(r"\A---[ \t]*\n(.*?)\n---[ \t]*\n?", md, re.S)
    return (m.group(1), md[m.end():]) if m else ("", md)
def strip_h1(md):
    lines = md.split("\n")
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
        if lines and lines[0].strip() == "": lines = lines[1:]
    return "\n".join(lines)

vmd = rd("vault.md") or ""; fm, vbody = strip_fm(vmd)
m_h1 = re.search(r"(?m)^#\s+(.+?)\s*$", vbody); title = m_h1.group(0) if m_h1 else "# Vault"
vbody_noh1 = strip_h1(vbody.lstrip("\n"))
# frontmatter: keep every lock scalar verbatim; re-key the layout marker and the doc identity
fm_lines = []
seen_layout = False
for ln in fm.splitlines():
    if re.match(r"^vault_layout:\s*", ln): fm_lines.append("vault_layout: 3"); seen_layout = True; continue
    if re.match(r"^type:\s*vault\s*$", ln): fm_lines.append("type: context"); continue
    if re.match(r"^doc_id:\s*vault\s*$", ln): fm_lines.append("doc_id: context"); continue
    fm_lines.append(ln)
if not seen_layout: fm_lines.insert(0, "vault_layout: 3")

overview, rest = cut_section(vbody_noh1, "Overview")
arch, rest = cut_section(rest, "Architecture")
decisions, rest = cut_section(rest, "Decisions")
dead = {}
for name in ("Glossary", "Source documents", "Auto-Classification Review", "Changelog"):
    body, rest = cut_section(rest, name)
    if body and body.strip(): dead[name] = body
leftover = [h for h, _, _ in sections(rest)]
def fold(md):
    """A layout-2 doc's OWN H2 grouping headings (`## User flows (web)`, `## Entities (DBML)`,
    `## Sources`, …) would become siblings of the layout-3 H2 contract and END the section
    the parsers slice (v3_section). They are kept VERBATIM as bold labels instead; H3+
    (`### F-001`, `### D-001`) stay untouched — that is the grammar the parsers key on."""
    return re.sub(r"(?m)^##\s+(.+?)\s*$", lambda m: "**%s**" % m.group(1), md)
flows = fold(strip_h1((rd("flows.md") or "").strip("\n")))
model = fold(strip_h1((rd("model.md") or "").strip("\n")))
cons_all = strip_h1((rd("constraints.md") or "").strip("\n"))
oq, cons = cut_section(cons_all, "Open Questions")
cons = fold(cons or "")

def sec(h, body): return "## %s\n\n%s" % (h, (body or "").strip("\n"))
parts = ["---\n" + "\n".join(fm_lines) + "\n---", title]
if overview and overview.strip(): parts.append(sec("Overview", overview))
if arch and arch.strip(): parts.append(sec("Architecture", arch))
parts.append(sec("Flows", flows or "(no flows doc in the layout-2 vault)"))
parts.append(sec("Data model", model or "(no data-model doc in the layout-2 vault)"))
parts.append(sec("Constraints", cons or "(no constraints doc in the layout-2 vault)"))
parts.append(sec("Open Questions", oq or "_none recorded_"))
if decisions and decisions.strip(): parts.append(sec("Decisions", decisions))
context = "\n\n".join(p.strip("\n") for p in parts) + "\n"

# ── binding split per unit (binding_refs → binding-migrated.json), never binding.json ──
bj = None
try:
    if os.path.isfile(os.path.join(vault, "binding.json")):
        bj = json.load(open(os.path.join(vault, "binding.json"), encoding="utf-8"))
except (OSError, ValueError):
    bj = None
claims_by_id = {c.get("id"): c for c in (bj or {}).get("claims", []) if isinstance(c, dict)}
bmd = rd("binding.md") or ""
def conflict_block(cid):
    m = re.search(r"(?ms)^###\s+[^\n]*\b%s\b[^\n]*\n(.*?)(?=^###\s|^##\s|\Z)" % re.escape(cid), bmd)
    return (m.group(0).strip("\n") if m else None)
splits = {}
for uf in sorted(glob.glob(os.path.join(vault, "units", "U-*.md"))):
    uid = os.path.basename(uf)[:-3]
    txt = open(uf, encoding="utf-8", errors="surrogateescape").read()
    fmu = re.match(r"\A---[ \t]*\n(.*?)\n---", txt, re.S)
    refs = []
    if fmu:
        mm = re.search(r"(?ms)^binding_refs:[ \t]*(\[[^\]]*\])?[ \t]*\n((?:[ \t]+-[^\n]*\n?)*)", fmu.group(1) + "\n")
        if mm:
            if mm.group(1): refs = [r.strip().strip("'\"") for r in mm.group(1)[1:-1].split(",") if r.strip()]
            else: refs = [re.sub(r"^[ \t]+-[ \t]*", "", ln).strip().strip("'\"") for ln in mm.group(2).splitlines() if ln.strip()]
    if not refs: continue
    entry = {"schema": "unit-binding-migrated/1", "unit": uid, "migrated_from": "binding.md + binding.json (layout-2)",
             "head_at_bind": (bj or {}).get("head"), "claims": [], "conflicts": [], "oq_refs": []}
    for r in refs:
        if r in claims_by_id:
            c = claims_by_id[r]
            entry["claims"].append({k: c.get(k) for k in ("id", "verdict", "state", "state_reason", "anchor", "confidence", "vault_source", "resolution")})
        elif r.startswith("CONFLICT-"):
            entry["conflicts"].append({"id": r, "block": conflict_block(r)})
        else:
            entry["oq_refs"].append(r)
    splits[uid] = entry

archive = os.path.join(vault, "_meta", "archive", "layout2")
to_archive = [n for n in ("vault.md", "model.md", "flows.md", "constraints.md", "binding.md", "binding.json", "claims-ledger.json") if os.path.isfile(os.path.join(vault, n))]
act = "write" if apply_ else "[dry-run] write"
print("  %s %s (%d bytes; sections: %s)" % (act, os.path.join(vault, "context.md"), len(context.encode("utf-8")),
      ", ".join(h for h, _, _ in sections(context))))
for uid, e in splits.items():
    print("  %s %s (%d claim(s), %d conflict(s), %d oq ref(s))" % (act, os.path.join(vault, "bolts", uid, "binding-migrated.json"), len(e["claims"]), len(e["conflicts"]), len(e["oq_refs"])))
for n in to_archive:
    print("  %s %s -> %s" % ("archive" if apply_ else "[dry-run] archive", os.path.join(vault, n), os.path.join(archive, n)))
if dead: print("  ARCHIVED-ONLY vault.md sections (not part of the layout-3 contract): " + "; ".join(dead))
if leftover: print("  DROPPED vault.md sections (unknown H2 — review before --apply, they stay in the archived vault.md): " + "; ".join(leftover))
if apply_:
    with open(os.path.join(vault, "context.md"), "w", encoding="utf-8", errors="surrogateescape") as f: f.write(context)
    for uid, e in splits.items():
        d = os.path.join(vault, "bolts", uid); os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "binding-migrated.json"), "w", encoding="utf-8") as f: json.dump(e, f, indent=1, ensure_ascii=False)
    os.makedirs(archive, exist_ok=True)
    def tracked(p):
        return subprocess.run(["git", "-C", cwd, "ls-files", "--error-unmatch", p], capture_output=True, timeout=30).returncode == 0
    for n in to_archive:
        src = os.path.join(vault, n); dst = os.path.join(archive, n)
        if tracked(src): subprocess.run(["git", "-C", cwd, "mv", "-f", src, dst], check=True, timeout=30)
        else: os.replace(src, dst)
    # NAME-only doc-ref rewrite in units + VAULT-DIFF (line anchors untouched — the re-bind is the honest fix)
    for f in sorted(glob.glob(os.path.join(vault, "units", "*.md"))) + [os.path.join(vault, "VAULT-DIFF.md")]:
        if not os.path.isfile(f): continue
        t = open(f, encoding="utf-8", errors="surrogateescape").read()
        t2 = re.sub(r"(?<![\w/.-])(?:vault|model|flows|constraints)\.md(?=#|:|\s|$)", "context.md", t)
        if t2 != t:
            with open(f, "w", encoding="utf-8", errors="surrogateescape") as fh: fh.write(t2)
PYEOF
[ "$RC" -eq 0 ] || { echo "migrate-vault-layout3: transform failed on $VAULT (rc=$RC)" >&2; exit 1; }
if [ "$APPLY" -eq 1 ]; then
  bash "${SCRIPT_DIR}/derive-vault-json.sh" --vault="$VAULT" || { echo "migrate-vault-layout3: derive-vault-json FAILED after migration of $VAULT" >&2; exit 1; }
  echo ""
  echo "NEXT (MANDATORY): full JIT re-bind required — the whole-vault binding was archived,"
  echo "  bolts/U-XXX/binding.json is regenerated from ground truth, never patched:"
  echo "    bash <plugin-root>/scripts/rebind-units.sh --cwd=<root> --vault=$VAULT --units=all"
  echo "  (or let execute-bolts --all --lite JIT-bind each unit at dispatch). Prior verdicts and"
  echo "  human resolutions are preserved per unit in bolts/U-XXX/binding-migrated.json."
else
  echo ""
  echo "Preview only — nothing changed. Re-run with --apply to execute."
fi
exit 0
