#!/usr/bin/env bash
# stamp-binding-boilerplate.sh — inject the static binding.md boilerplate
# (P2b, spec 2026-07-19-batch2-derive-and-diet.md): the do-not-hand-edit banner
# + the keterangan enum legend are STAMPED post-write by this script — the
# model never types them (bind Step 4.5, BEFORE derive-binding-json.sh).
#
# Contract:
#   - Pure-additive + idempotent: re-running on a stamped file is a byte-
#     identical no-op.
#   - Parser-invisible: the banner (between frontmatter and `# Binding
#     Manifest`) and the legend blockquote (under the `## Conflicts` heading,
#     BEFORE any `### CONFLICT-N` detail heading) sit outside every region
#     `_lib/binding_md.py` reads — binding.json is byte-identical whether
#     derived before or after stamping.
#   - Zero-conflict binding.md (no `## Conflicts` heading): banner stamped,
#     legend skipped gracefully, exit 0.
#   - Atomic write (compose full content, tmp + os.replace) — a crash never
#     leaves a truncated binding.md.
#
# The 4-code gloss text below is the SINGLE SOURCE of the enum legend
# (keterangan contract) — binding.md is a durable Tier-3 artifact (English);
# the DISPLAYER localizes at prompt time per halt-protocol §Consumer dispatch
# step 0. Never duplicate the gloss into templates/skills.
#
# Usage: stamp-binding-boilerplate.sh --vault <dir>   (dir containing binding.md)
# Exit: 0 = stamped (or already stamped); 3 = usage / unreadable binding.md.
set -u

VAULT=""
while [ $# -gt 0 ]; do case "$1" in --vault) VAULT="${2:-}"; shift 2;; --vault=*) VAULT="${1#*=}"; shift;; *) shift;; esac; done
[ -n "$VAULT" ] || { echo "usage: stamp-binding-boilerplate.sh --vault <dir>" >&2; exit 3; }

V_VAULT="$VAULT" python3 <<'PYEOF'
import os, sys

vault = os.environ.get("V_VAULT") or ""
md_path = os.path.join(vault, "binding.md")
try:
    md = open(md_path, encoding="utf-8").read()
except Exception as e:
    print(f"FAIL: cannot read binding.md: {e}", file=sys.stderr)
    sys.exit(3)

BANNER = (
    "> REGENERATED by bind-codebase on every run — do NOT hand-edit. Manual "
    "verdict edits are LOST on re-bind; CONFLICT resolutions belong in "
    "`resolve-oq --binding` (which records them durably in decisions.md)."
)

LEGEND = "\n".join([
    "> **Enum legend (keterangan contract).** binding.md is a durable ARTIFACT — the legend below is",
    "> written in English here (Tier-3: artifact language, per output-language.md); the DISPLAYER",
    "> localizes it at prompt time (halt-protocol §Consumer dispatch step 0 / the resolve-oq",
    "> --binding menu carry the Tier-2 rendering). Codes stay English everywhere (Tier-1).",
    "> KEEP_VAULT = the vault is right; code must change to match (patch lands later).",
    "> KEEP_CODE = the vault is wrong; the vault is updated to match code reality.",
    "> DEFER = downgraded to an OQ; the binding gate OPENS and units generate carrying the OQ",
    "> (execute-bolts prompts at the unit's \"TBD: OQ-XXX\" before the bolt finalizes).",
    "> SPLIT = the claim is split into sub-claims, each re-bound separately.",
])

changed = False

# ── Banner: first line after the frontmatter (or file top when no frontmatter) ──
if "REGENERATED by bind-codebase on every run" not in md:
    if md.startswith("---"):
        end = md.find("\n---", 3)
        if end != -1:
            nl = md.find("\n", end + 1)
            insert_at = (nl + 1) if nl != -1 else len(md)
        else:
            insert_at = 0  # malformed frontmatter — stamp at top, stay additive
    else:
        insert_at = 0
    head, tail = md[:insert_at], md[insert_at:]
    md = head + BANNER + "\n\n" + tail.lstrip("\n")
    changed = True

# ── Legend: under the `## Conflicts` heading (skipped when absent — zero-conflict bind) ──
if "Enum legend (keterangan contract" not in md:
    lines = md.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.strip().startswith("## Conflicts"):
            rest = "".join(lines[i + 1:]).lstrip("\n")
            md = "".join(lines[: i + 1]) + "\n" + LEGEND + "\n\n" + rest
            changed = True
            break

if not changed:
    print("PASS: binding.md already stamped (idempotent no-op)")
    sys.exit(0)

tmp = md_path + ".tmp"
with open(tmp, "w", encoding="utf-8") as f:
    f.write(md)
os.replace(tmp, md_path)
legend_note = "banner + legend" if "Enum legend (keterangan contract" in md else "banner (no ## Conflicts heading — legend skipped)"
print(f"PASS: stamped binding.md ({legend_note})")
sys.exit(0)
PYEOF
