#!/usr/bin/env bash
# 8.0.3 — provenance trailer is TWO lines (marker + `Unit: U-XXX · provenance: <dispatch-prompt.md path>`).
# The moat check `provenance_missing` (validate-bolt-artifacts.sh Check 1) keys on the marker line
# in the first 30 lines and is UNCHANGED — this pins both the new shape and the guard:
#   a  new-format trailer → provenance_missing does NOT fire
#   b  file without the marker line → provenance_missing FIRES (regression guard = the moat)
#   c  marker at line 25 → passes; marker at line 35 → fires (30-line window still applies)
#   d  agents/bolt-implementer.md no longer instructs `Hard Rules active:` / `Implements claim:` /
#      `Anchors consulted:` / `vault sha256` inside the trailer; line 2 = Unit · provenance pointer
#   e  Iron Rule 6 protect-list still names the provenance trailer as "Never strip"
#   f  the dispatch builder emits `provenance_path:` in the Provenance values block and a COUNT
#      (not the verbatim list) for hard_rules_active
# Run: bash tests/comment-diet/test-provenance-trailer-2line.sh </dev/null
set -u
rc=0; pass() { echo "PASS: $1"; }; fail() { echo "FAIL: $1"; rc=1; }
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"; P="$ROOT/plugins/mega-sdd"; VBA="$P/scripts/validate-bolt-artifacts.sh"
T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
V="$T/.mega-sdd/vaults/app"; mkdir -p "$V/units" "$V/bolts/U-001" "$T/src"; ( cd "$T" && git init -q . )
printf -- '---\nid: U-001\ntitle: t\ntask_type: create\ntarget_files:\n  - path: src/a.ts\n    operation: create\n---\n# u\n' > "$V/units/U-001.md"
printf '# dispatch\n' > "$V/bolts/U-001/dispatch-prompt.md"
run() { bash "$VBA" --cwd="$T" --file-path="$T/src/a.ts" 2>/dev/null; }
# a — new format
printf '// Generated by mega-sdd execute-bolts 8.0.3\n// Unit: U-001 · provenance: .mega-sdd/vaults/app/bolts/U-001/dispatch-prompt.md\n\nexport const a = 1\n' > "$T/src/a.ts"
OUT="$(run)"; RC=$?
[ $RC -eq 0 ] && ! echo "$OUT" | grep -q provenance_missing && pass "a: two-line trailer (marker + Unit · provenance pointer) → provenance_missing does not fire (rc=0)" || fail "a: rc=$RC $OUT"
# b — no marker
printf '// Unit: U-001 · provenance: .mega-sdd/vaults/app/bolts/U-001/dispatch-prompt.md\nexport const a = 1\n' > "$T/src/a.ts"
OUT="$(run)"; RC=$?
[ $RC -eq 1 ] && echo "$OUT" | grep -q provenance_missing && pass "b: marker line absent → provenance_missing FIRES (rc=1) — the moat guard" || fail "b: rc=$RC $OUT"
# c — window
{ for i in $(seq 1 24); do echo "// pad $i"; done; echo '// Generated by mega-sdd execute-bolts 8.0.3'; echo '// Unit: U-001'; echo 'export const a = 1'; } > "$T/src/a.ts"
OUT="$(run)"; RC=$?; [ $RC -eq 0 ] && pass "c1: marker at line 25 → passes" || fail "c1: rc=$RC"
{ for i in $(seq 1 34); do echo "// pad $i"; done; echo '// Generated by mega-sdd execute-bolts 8.0.3'; echo 'export const a = 1'; } > "$T/src/a.ts"
OUT="$(run)"; RC=$?; [ $RC -eq 1 ] && echo "$OUT" | grep -q provenance_missing && pass "c2: marker at line 35 → fires (30-line window unchanged)" || fail "c2: rc=$RC"
# d — implementer contract
IMPL="$P/agents/bolt-implementer.md"
grep -q 'Unit: U-XXX · provenance:' "$IMPL" && grep -q 'TWO lines, never more' "$IMPL" && ! grep -q '^Hard Rules active:' "$IMPL" && ! grep -q '^Implements claim:' "$IMPL" && ! grep -q '^Anchors consulted:' "$IMPL" && ! grep -q '^Unit: U-XXX (vault sha256' "$IMPL" \
  && pass "d: implementer trailer = marker + 'Unit · provenance' only; old lines gone" || fail "d: implementer contract"
grep -q 'Generated by mega-sdd execute-bolts` marker line is never omitted' "$IMPL" && grep -q 'never guess or back-derive' "$IMPL" && grep -q 'provenance_missing' "$IMPL" \
  && pass "d2: marker never omitted + no-guessing + provenance_missing halt kept" || fail "d2: kept clauses"
# e — protect-list
grep -q 'Never strip\*\* the mega-sdd provenance trailer' "$IMPL" && pass "e: Iron Rule 6 protect-list still names the provenance trailer" || fail "e: protect-list"
# f — builder block
grep -q 't1.append("  provenance_path: %s"' "$P/scripts/build-dispatch-prompt.sh" && grep -q 'hard_rules_active: %d mechanical rule(s)' "$P/scripts/build-dispatch-prompt.sh" && ! grep -q 't1.append("    - %s" % r)' "$P/scripts/build-dispatch-prompt.sh" \
  && pass "f: builder emits provenance_path + hard_rules_active COUNT (verbatim list gone)" || fail "f: builder block"
echo; [ $rc -eq 0 ] && echo "ALL PASS" || echo "FAILURES PRESENT"; exit $rc
