#!/usr/bin/env bash
# Team feedback #4 (runbook §5 masukan tim #4, 2026-09-15): generated code carried over-verbose
# comments. Diagnosis (research/2026-09-15-v8-p3-report.md §6): the panel never rewarded comments
# (0 mentions), the laravel-base-26 pack REWARDED docblocks ("prefer PHPDoc blocks"), the rest was
# model default with no rule. This pins the STYLE rule (never a gate — F.5: no comment-counting
# validator) at every surface that could ask for or reward comments:
#   (a, i–l, n–r pinned Iron Rule 6 in agents/bolt-implementer.md — deleted in P3 C6b, spec v9
#    §8.6 G1: the rule no longer reaches implement time; b, m and s keep the _universal.md mirror.)
#   b  _universal.md carries the same rule as the pack default + the protected list
#   c  laravel-base-26.md no longer says "prefer PHPDoc blocks" (the measured reward trigger)
#   (d, e, u pinned the quality/standards lens agents — deleted in P3 C3.)
#   f  no other pack rewards docblocks/comments as a blanket rule
#   g  the provenance trailer stays MANDATORY (the enforcement doc + the inline plan's implement
#      step; gate-read by validate-bolt-artifacts.sh `provenance_missing`) — the diet never removes it
#   t1–t3 8.0.2 — the trailer is TWO lines (marker + Unit); dropped lines had zero readers; gate key unchanged
#   h  no comment-counting validator exists (F.5) — no script names a comment-ratio gate
#   m  8.0.3 decision test, _universal mirror
#   s  8.1.0 code-style playbook (spec 2026-09-16), _universal mirror (+ NO ## Code style of its own)
# Run: bash tests/comment-diet/test-comment-why-rule.sh </dev/null
set -u
rc=0; pass() { echo "PASS: $1"; }; fail() { echo "FAIL: $1"; rc=1; }
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"; P="$ROOT/plugins/mega-sdd"
HH="$P/skills/execute-bolts/references/halts-and-handoff.md"; UNI="$P/references/framework-conventions/_universal.md"
L26="$P/references/framework-conventions/laravel-base-26.md"

grep -q '^## Comment conventions' "$UNI" && grep -q 'explains \*\*WHY\*\*, never WHAT' "$UNI" && grep -q 'Protected (load-bearing, never stripped)' "$UNI" \
  && grep -q 'Generated by mega-sdd execute-bolts' "$UNI" && grep -q 'never reports "missing comment/docblock"' "$UNI" \
  && pass "b: _universal.md pack default carries the rule + protected list + panel stance" || fail "b: _universal.md"
! grep -q 'prefer PHPDoc blocks' "$L26" && grep -q 'Comments explain WHY, never WHAT' "$L26" && grep -q 'ONLY where the toolchain consumes it' "$L26" \
  && pass "c: laravel-base-26 no longer rewards docblocks; PHPDoc scoped to toolchain-consumed surfaces" || fail "c: laravel-base-26"
HITS="$(grep -l -i -E 'prefer (php|js)doc|docblock (on|for) every|document every (method|function|class)|add (php|js)doc(s)? to all' "$P"/references/framework-conventions/*.md 2>/dev/null | grep -v '_universal.md' || true)"
[ -z "$HITS" ] && pass "f: no pack carries a blanket 'docblock everything' reward" || fail "f: packs still reward docblocks: $HITS"
grep -q '^## Provenance trailer enforcement' "$HH" && grep -qF 'starts with the provenance header' "$P/scripts/derive-exec-plan.sh" && grep -q 'Generated by mega-sdd execute-bolts' "$P/scripts/validate-bolt-artifacts.sh" \
  && pass "g: provenance trailer stays mandatory + gate-read (protected, untouched by the diet)" || fail "g: provenance trailer contract moved"
! grep -rl -i -E 'comment[-_ ]ratio|comment_lines|max_comment' "$P/scripts" "$P/hooks" 2>/dev/null | grep -q . \
  && pass "h: no comment-counting validator/gate exists (F.5: style rule, not a gate)" || fail "h: a comment-counting gate appeared"
# t1/t2/t3 — 8.0.2/8.0.3: the trailer contract is TWO lines; the dropped labels are gone from the
#     enforcement doc, NO script/hook reads them, the gate key is unchanged
grep -q 'provenance trailer comment — TWO lines' "$HH" && ! grep -q '^Implements claim: C-NNN' "$HH" && ! grep -q '^Anchors consulted: <list>' "$HH" && ! grep -q '^Hard Rules active:' "$HH" \
  && pass "t1: trailer contract = marker + Unit only (enforcement doc); dropped labels gone" || fail "t1: trailer contract"
! grep -rn -F -e 'Implements claim:' -e 'Anchors consulted:' -e 'Hard Rules active:' "$P/scripts" "$P/hooks" --include='*.sh' --include='*.py' 2>/dev/null | grep -v '^[^:]*:[0-9]*:#' | grep -q . \
  && pass "t2: no script/hook READS a dropped trailer line (only comments mention them)" || fail "t2: a reader of a dropped trailer line exists"
# t3 — the gate still keys on the marker line only (validate-bolt-artifacts.sh provenance_missing)
grep -q 'if "Generated by mega-sdd execute-bolts" not in head' "$P/scripts/validate-bolt-artifacts.sh" && grep -q '"halt_type": "provenance_missing"' "$P/scripts/validate-bolt-artifacts.sh" \
  && pass "t3: provenance_missing gate unchanged — marker line in the first 30 lines" || fail "t3: gate key drifted"
# m — 8.0.3 item 3 (the decision test) as the _universal.md pack default
grep -q 'an OPEN list' "$UNI" && grep -q 'The delete test decides every case' "$UNI" && grep -q 'In doubt → not written' "$UNI" && grep -q 'Minimality for the comments that pass' "$UNI" && grep -q 'a full docblock only when a toolchain reads it' "$UNI" \
  && pass "m: _universal.md §Comment conventions carries the same three clauses" || fail "m: _universal.md clauses"
# s — 8.1.0 code-style playbook R1 (docs/superpowers/specs/2026-09-16-code-style-playbook-design.md §4), _universal mirror
grep -q 'crosses a module/team boundary' "$UNI" && grep -q 'Comment language follows the surrounding code' "$UNI" \
  && grep -q 'thread-safety' "$UNI" && grep -q 'non-public members whose name already says it' "$UNI" \
  && grep -q 'Code style (self-documenting)' "$UNI" && ! grep -q '^## Code style' "$UNI" \
  && pass "s: _universal.md mirrors n/o/p and points at the pack ## Code style — carrying NO such section itself" || fail "s: _universal mirror"
echo; [ $rc -eq 0 ] && echo "ALL PASS" || echo "FAILURES PRESENT"; exit $rc
