#!/usr/bin/env bash
# 8.0.3 — provenance trailer is TWO lines (marker + `Unit: U-XXX · provenance: <dispatch-prompt.md path>`).
# The moat check `provenance_missing` (validate-bolt-artifacts.sh Check 1) keys on the marker line
# in the first 30 lines and is UNCHANGED — this pins both the new shape and the guard:
#   a  new-format trailer → provenance_missing does NOT fire
#   b  file without the marker line → provenance_missing FIRES (regression guard = the moat)
#   c  marker at line 25 → passes; marker at line 35 → fires (30-line window still applies)
#   (d, d2, e pinned the trailer contract in agents/bolt-implementer.md — deleted in P3 C6b,
#    spec v9 §8.6; the gate key below and halts-and-handoff.md §Provenance trailer enforcement stay.)
#   g  validate-bolt-artifacts.sh key strings unchanged (marker + bolt_self_report:),
#      carried from tests/boilerplate-diet/test-p2d-agent-contracts.sh §4
# Run: bash tests/comment-diet/test-provenance-trailer-2line.sh </dev/null
set -u
rc=0; pass() { echo "PASS: $1"; }; fail() { echo "FAIL: $1"; rc=1; }
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"; P="$ROOT/plugins/mega-sdd"; VBA="$P/scripts/validate-bolt-artifacts.sh"
T="$(mktemp -d)"; trap 'rm -rf "$T"' EXIT
V="$T/.mega-sdd/vaults/app"; mkdir -p "$V/units" "$V/bolts/U-001" "$T/src"; ( cd "$T" && git init -q . )
printf -- '---\nid: U-001\ntitle: t\ntask_type: create\ntarget_files:\n  - path: src/a.ts\n    operation: create\n---\n# u\n' > "$V/units/U-001.md"
printf '# dispatch\n' > "$V/bolts/U-001/dispatch-prompt.md"
run() { bash "$VBA" --cwd="$T" --file-path="$T/src/a.ts" 2>/dev/null; }
# a — new format
printf '// Generated by mega-sdd execute-bolts 8.0.3\n// Unit: U-001 · provenance: .mega-sdd/vaults/app/bolts/U-001/dispatch-prompt.md\n\nexport const a = 1\n' > "$T/src/a.ts"
OUT="$(run)"; RC=$?
[ $RC -eq 0 ] && ! echo "$OUT" | grep -q provenance_missing && pass "a: two-line trailer (marker + Unit · provenance pointer) → provenance_missing does not fire (rc=0)" || fail "a: rc=$RC $OUT"
# b — no marker
printf '// Unit: U-001 · provenance: .mega-sdd/vaults/app/bolts/U-001/dispatch-prompt.md\nexport const a = 1\n' > "$T/src/a.ts"
OUT="$(run)"; RC=$?
[ $RC -eq 1 ] && echo "$OUT" | grep -q provenance_missing && pass "b: marker line absent → provenance_missing FIRES (rc=1) — the moat guard" || fail "b: rc=$RC $OUT"
# c — window
{ for i in $(seq 1 24); do echo "// pad $i"; done; echo '// Generated by mega-sdd execute-bolts 8.0.3'; echo '// Unit: U-001'; echo 'export const a = 1'; } > "$T/src/a.ts"
OUT="$(run)"; RC=$?; [ $RC -eq 0 ] && pass "c1: marker at line 25 → passes" || fail "c1: rc=$RC"
{ for i in $(seq 1 34); do echo "// pad $i"; done; echo '// Generated by mega-sdd execute-bolts 8.0.3'; echo 'export const a = 1'; } > "$T/src/a.ts"
OUT="$(run)"; RC=$?; [ $RC -eq 1 ] && echo "$OUT" | grep -q provenance_missing && pass "c2: marker at line 35 → fires (30-line window unchanged)" || fail "c2: rc=$RC"
# g — validator key strings
grep -qF '"Generated by mega-sdd execute-bolts" not in head' "$VBA" \
  && pass "g1: validator provenance marker key unchanged" || fail "g1: validator marker key drifted"
grep -qF '"bolt_self_report:" not in content' "$VBA" \
  && pass "g2: validator self-report key unchanged" || fail "g2: validator self-report key drifted"
echo; [ $rc -eq 0 ] && echo "ALL PASS" || echo "FAILURES PRESENT"; exit $rc
