#!/usr/bin/env bash
# Team feedback #4 (runbook §5 masukan tim #4, 2026-09-15): generated code carried over-verbose
# comments. Diagnosis (research/2026-09-15-v8-p3-report.md §6): the panel never rewarded comments
# (0 mentions), the laravel-base-26 pack REWARDED docblocks ("prefer PHPDoc blocks"), the rest was
# model default with no rule. This pins the STYLE rule (never a gate — F.5: no comment-counting
# validator) at every surface that could ask for or reward comments:
#   a  bolt-implementer.md carries the rule "Comments explain WHY, never WHAT" + the forbidden
#      classes + the protected list (provenance trailer, // source: anchors, validator-read
#      citations, pack-required headers)
#   b  _universal.md carries the same rule as the pack default + the protected list
#   c  laravel-base-26.md no longer says "prefer PHPDoc blocks" (the measured reward trigger)
#   d  code-quality-reviewer.md: WHAT-comment = Minor (tag comment-what:), missing comment ≠ finding
#   e  standards-reviewer.md forbids "missing docblock/comment" findings
#   f  no other pack rewards docblocks/comments as a blanket rule
#   g  the provenance trailer stays MANDATORY in the implementer (protected, gate-read by
#      validate-bolt-artifacts.sh `provenance_missing`) — the diet never removes it
#   i/j 8.0.2 — the trailer is TWO lines (marker + Unit); dropped lines had zero readers; gate key unchanged
#   h  no comment-counting validator exists (F.5) — no script names a comment-ratio gate
# Run: bash tests/comment-diet/test-comment-why-rule.sh </dev/null
set -u
rc=0; pass() { echo "PASS: $1"; }; fail() { echo "FAIL: $1"; rc=1; }
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"; P="$ROOT/plugins/mega-sdd"
IMPL="$P/agents/bolt-implementer.md"; UNI="$P/references/framework-conventions/_universal.md"
L26="$P/references/framework-conventions/laravel-base-26.md"; QL="$P/agents/code-quality-reviewer.md"; SL="$P/agents/standards-reviewer.md"

grep -q 'Comments explain WHY, never WHAT' "$IMPL" && grep -q 'restate the signature' "$IMPL" && grep -q 'Step 1: validate input' "$IMPL" \
  && grep -q 'Never strip' "$IMPL" && grep -q '// source: <path>:<line>' "$IMPL" && grep -q 'license/compliance header' "$IMPL" \
  && pass "a: implementer carries WHY-not-WHAT + forbidden classes + protected list" || fail "a: implementer rule"
grep -q '^## Comment conventions' "$UNI" && grep -q 'explains \*\*WHY\*\*, never WHAT' "$UNI" && grep -q 'Protected (load-bearing, never stripped)' "$UNI" \
  && grep -q 'Generated by mega-sdd execute-bolts' "$UNI" && grep -q 'never reports "missing comment/docblock"' "$UNI" \
  && pass "b: _universal.md pack default carries the rule + protected list + panel stance" || fail "b: _universal.md"
! grep -q 'prefer PHPDoc blocks' "$L26" && grep -q 'Comments explain WHY, never WHAT' "$L26" && grep -q 'ONLY where the toolchain consumes it' "$L26" \
  && pass "c: laravel-base-26 no longer rewards docblocks; PHPDoc scoped to toolchain-consumed surfaces" || fail "c: laravel-base-26"
grep -q 'Comment noise (WHAT-comments) — Minor, never higher' "$QL" && grep -q 'comment-what:' "$QL" && grep -q 'A \*missing\* comment or docblock is NOT a finding' "$QL" \
  && pass "d: quality lens grades WHAT-comments Minor and never reports missing docs" || fail "d: quality lens"
grep -q '"Missing docblock / missing comment / undocumented method" — never a finding' "$SL" \
  && pass "e: standards lens forbids missing-docblock findings" || fail "e: standards lens"
HITS="$(grep -l -i -E 'prefer (php|js)doc|docblock (on|for) every|document every (method|function|class)|add (php|js)doc(s)? to all' "$P"/references/framework-conventions/*.md 2>/dev/null | grep -v '_universal.md' || true)"
[ -z "$HITS" ] && pass "f: no pack carries a blanket 'docblock everything' reward" || fail "f: packs still reward docblocks: $HITS"
grep -q '## Provenance trailer (MANDATORY in every file you modify' "$IMPL" && grep -q 'Generated by mega-sdd execute-bolts' "$P/scripts/validate-bolt-artifacts.sh" \
  && pass "g: provenance trailer stays mandatory + gate-read (protected, untouched by the diet)" || fail "g: provenance trailer contract moved"
! grep -rl -i -E 'comment[-_ ]ratio|comment_lines|max_comment' "$P/scripts" "$P/hooks" 2>/dev/null | grep -q . \
  && pass "h: no comment-counting validator/gate exists (F.5: style rule, not a gate)" || fail "h: a comment-counting gate appeared"
# i — 8.0.2: the trailer contract is TWO lines (marker + Unit); the three dropped labels are gone
#     from the implementer + the enforcement doc, and NO script/hook reads them
grep -q 'TWO lines, never more' "$IMPL" && ! grep -q '^Implements claim: C-NNN' "$IMPL" && ! grep -q '^Anchors consulted: <list>' "$IMPL" && ! grep -q '^Hard Rules active:' "$IMPL" \
  && ! grep -q '^Implements claim: C-NNN' "$P/skills/execute-bolts/references/halts-and-handoff.md" \
  && pass "i: trailer contract = marker + Unit only (implementer + enforcement doc); dropped labels gone" || fail "i: trailer contract"
! grep -rn -F -e 'Implements claim:' -e 'Anchors consulted:' -e 'Hard Rules active:' "$P/scripts" "$P/hooks" --include='*.sh' --include='*.py' 2>/dev/null | grep -v '^[^:]*:[0-9]*:#' | grep -q . \
  && pass "i2: no script/hook READS a dropped trailer line (only comments mention them)" || fail "i2: a reader of a dropped trailer line exists"
# j — the gate still keys on the marker line only (validate-bolt-artifacts.sh provenance_missing)
grep -q 'if "Generated by mega-sdd execute-bolts" not in head' "$P/scripts/validate-bolt-artifacts.sh" && grep -q '"halt_type": "provenance_missing"' "$P/scripts/validate-bolt-artifacts.sh" \
  && pass "j: provenance_missing gate unchanged — marker line in the first 30 lines" || fail "j: gate key drifted"
echo; [ $rc -eq 0 ] && echo "ALL PASS" || echo "FAILURES PRESENT"; exit $rc
