#!/usr/bin/env bash
# Team feedback #4 (runbook §5 masukan tim #4, 2026-09-15): generated code carried over-verbose
# comments. Diagnosis (research/2026-09-15-v8-p3-report.md §6): the panel never rewarded comments
# (0 mentions), the laravel-base-26 pack REWARDED docblocks ("prefer PHPDoc blocks"), the rest was
# model default with no rule. This pins the STYLE rule (never a gate — F.5: no comment-counting
# validator) at every surface that could ask for or reward comments:
#   a  bolt-implementer.md carries the rule "Comments explain WHY, never WHAT" + the forbidden
#      classes + the protected list (provenance trailer, // source: anchors, validator-read
#      citations, pack-required headers)
#   b  _universal.md carries the same rule as the pack default + the protected list
#   c  laravel-base-26.md no longer says "prefer PHPDoc blocks" (the measured reward trigger)
#   d  code-quality-reviewer.md: WHAT-comment = Minor (tag comment-what:), missing comment ≠ finding
#   e  standards-reviewer.md forbids "missing docblock/comment" findings
#   f  no other pack rewards docblocks/comments as a blanket rule
#   g  the provenance trailer stays MANDATORY in the implementer (protected, gate-read by
#      validate-bolt-artifacts.sh `provenance_missing`) — the diet never removes it
#   i/j 8.0.2 — the trailer is TWO lines (marker + Unit); dropped lines had zero readers; gate key unchanged
#   h  no comment-counting validator exists (F.5) — no script names a comment-ratio gate
#   n–u 8.1.0 code-style playbook (spec 2026-09-16): OPEN-1 boundary-crossing public-API licence, OPEN-2
#      comment language = surrounding code, skip/allow additions, "Names do the explaining", self-review
#      Comments check, _universal mirror (+ NO ## Code style of its own), quality lens comment-what shapes
# Run: bash tests/comment-diet/test-comment-why-rule.sh </dev/null
set -u
rc=0; pass() { echo "PASS: $1"; }; fail() { echo "FAIL: $1"; rc=1; }
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"; P="$ROOT/plugins/mega-sdd"
IMPL="$P/agents/bolt-implementer.md"; UNI="$P/references/framework-conventions/_universal.md"
L26="$P/references/framework-conventions/laravel-base-26.md"; QL="$P/agents/code-quality-reviewer.md"; SL="$P/agents/standards-reviewer.md"

grep -q 'Comments explain WHY, never WHAT' "$IMPL" && grep -q 'restate the signature' "$IMPL" && grep -q 'Step 1: validate input' "$IMPL" \
  && grep -q 'Never strip' "$IMPL" && grep -q '// source: <path>:<line>' "$IMPL" && grep -q 'license/compliance header' "$IMPL" \
  && pass "a: implementer carries WHY-not-WHAT + forbidden classes + protected list" || fail "a: implementer rule"
grep -q '^## Comment conventions' "$UNI" && grep -q 'explains \*\*WHY\*\*, never WHAT' "$UNI" && grep -q 'Protected (load-bearing, never stripped)' "$UNI" \
  && grep -q 'Generated by mega-sdd execute-bolts' "$UNI" && grep -q 'never reports "missing comment/docblock"' "$UNI" \
  && pass "b: _universal.md pack default carries the rule + protected list + panel stance" || fail "b: _universal.md"
! grep -q 'prefer PHPDoc blocks' "$L26" && grep -q 'Comments explain WHY, never WHAT' "$L26" && grep -q 'ONLY where the toolchain consumes it' "$L26" \
  && pass "c: laravel-base-26 no longer rewards docblocks; PHPDoc scoped to toolchain-consumed surfaces" || fail "c: laravel-base-26"
grep -q 'Comment noise (WHAT-comments) — Minor, never higher' "$QL" && grep -q 'comment-what:' "$QL" && grep -q 'A \*missing\* comment or docblock is NOT a finding' "$QL" \
  && pass "d: quality lens grades WHAT-comments Minor and never reports missing docs" || fail "d: quality lens"
grep -q '"Missing docblock / missing comment / undocumented method" — never a finding' "$SL" \
  && pass "e: standards lens forbids missing-docblock findings" || fail "e: standards lens"
HITS="$(grep -l -i -E 'prefer (php|js)doc|docblock (on|for) every|document every (method|function|class)|add (php|js)doc(s)? to all' "$P"/references/framework-conventions/*.md 2>/dev/null | grep -v '_universal.md' || true)"
[ -z "$HITS" ] && pass "f: no pack carries a blanket 'docblock everything' reward" || fail "f: packs still reward docblocks: $HITS"
grep -q '## Provenance trailer (MANDATORY in every file you modify' "$IMPL" && grep -q 'Generated by mega-sdd execute-bolts' "$P/scripts/validate-bolt-artifacts.sh" \
  && pass "g: provenance trailer stays mandatory + gate-read (protected, untouched by the diet)" || fail "g: provenance trailer contract moved"
! grep -rl -i -E 'comment[-_ ]ratio|comment_lines|max_comment' "$P/scripts" "$P/hooks" 2>/dev/null | grep -q . \
  && pass "h: no comment-counting validator/gate exists (F.5: style rule, not a gate)" || fail "h: a comment-counting gate appeared"
# t1/t2/t3 — 8.0.2/8.0.3: the trailer contract is TWO lines; the dropped labels are gone from the
#     implementer + the enforcement doc, NO script/hook reads them, the gate key is unchanged
grep -q 'TWO lines, never more' "$IMPL" && ! grep -q '^Implements claim: C-NNN' "$IMPL" && ! grep -q '^Anchors consulted: <list>' "$IMPL" && ! grep -q '^Hard Rules active:' "$IMPL" \
  && ! grep -q '^Implements claim: C-NNN' "$P/skills/execute-bolts/references/halts-and-handoff.md" \
  && pass "t1: trailer contract = marker + Unit only (implementer + enforcement doc); dropped labels gone" || fail "t1: trailer contract"
! grep -rn -F -e 'Implements claim:' -e 'Anchors consulted:' -e 'Hard Rules active:' "$P/scripts" "$P/hooks" --include='*.sh' --include='*.py' 2>/dev/null | grep -v '^[^:]*:[0-9]*:#' | grep -q . \
  && pass "t2: no script/hook READS a dropped trailer line (only comments mention them)" || fail "t2: a reader of a dropped trailer line exists"
# t3 — the gate still keys on the marker line only (validate-bolt-artifacts.sh provenance_missing)
grep -q 'if "Generated by mega-sdd execute-bolts" not in head' "$P/scripts/validate-bolt-artifacts.sh" && grep -q '"halt_type": "provenance_missing"' "$P/scripts/validate-bolt-artifacts.sh" \
  && pass "t3: provenance_missing gate unchanged — marker line in the first 30 lines" || fail "t3: gate key drifted"
# i–m — 8.0.3 item 3: from a closed ban-list to a decision test (owner): delete test + "in doubt → not
#       written", OPEN-list marker, minimality + toolchain condition, the four concrete bans KEPT,
#       and _universal.md carrying the same three clauses
grep -q 'The delete test decides every case' "$IMPL" && grep -q 'do they lose information? Not lost → not written' "$IMPL" && grep -q 'In doubt → not written' "$IMPL" \
  && pass "i: Iron Rule 6 carries the delete test AND 'in doubt → not written'" || fail "i: delete test / doubt clause"
grep -q 'That list is OPEN, not closed' "$IMPL" && pass "j: Iron Rule 6 marks the ban-list as OPEN (not closed)" || fail "j: open-list marker"
grep -q 'Minimality for the comments that pass' "$IMPL" && grep -q 'a full docblock only when a toolchain reads it' "$IMPL" && grep -q 'never add tags that restate the signature' "$IMPL" \
  && pass "k: Iron Rule 6 carries minimality + the toolchain-reads-it condition for full docblocks" || fail "k: minimality clause"
grep -q 'docblocks that restate the signature' "$IMPL" && grep -q 'Step 1: validate input' "$IMPL" && grep -q 'test-step narration that repeats the assertion' "$IMPL" && grep -q 'a header that repeats the file name' "$IMPL" \
  && pass "l: the four concrete bans are still present (docblock echo, // Step N, test-step narration, file-name header)" || fail "l: a concrete ban was lost"
grep -q 'an OPEN list' "$UNI" && grep -q 'The delete test decides every case' "$UNI" && grep -q 'In doubt → not written' "$UNI" && grep -q 'Minimality for the comments that pass' "$UNI" && grep -q 'a full docblock only when a toolchain reads it' "$UNI" \
  && pass "m: _universal.md §Comment conventions carries the same three clauses" || fail "m: _universal.md clauses"
# n–u — 8.1.0 code-style playbook R1 (docs/superpowers/specs/2026-09-16-code-style-playbook-design.md §4)
grep -q 'or on public API that crosses a module/team boundary' "$IMPL" && grep -q 'never the signature itself' "$IMPL" \
  && pass "n: Iron Rule 6 licence = toolchain reads it OR boundary-crossing public API; content = contract, never the signature (OPEN-1)" || fail "n: OPEN-1 licence"
grep -q 'Comment language follows the surrounding code' "$IMPL" && grep -q 'never two languages in one file' "$IMPL" \
  && pass "o: Iron Rule 6 — comment language follows the surrounding code (OPEN-2)" || fail "o: OPEN-2 comment language"
grep -q 'non-public members whose name already says it' "$IMPL" && grep -q 'overrides whose contract lives on the interface/base' "$IMPL" \
  && grep -q 'thread-safety or an exception the name does not imply' "$IMPL" && grep -q '`TODO`/`FIXME`' "$IMPL" && grep -q '`@throws`' "$IMPL" \
  && pass "p: Rule 6 skip-list (non-public, overrides) + allow-list (side effect / thread-safety / exception, FIXME) + @throws tag" || fail "p: skip/allow additions"
grep -q 'Names do the explaining' "$IMPL" && grep -q 'booleans read as a question' "$IMPL" && grep -q 'start with the verb' "$IMPL" \
  && grep -q 'collections are plural' "$IMPL" && grep -q '`data`, `temp`, `obj`' "$IMPL" \
  && pass "q: §Code organization carries 'Names do the explaining' + the four naming heuristics" || fail "q: naming paragraph"
grep -q '\*\*Comments\*\* — every comment I left survives the delete test' "$IMPL" \
  && pass "r: self-review carries the Comments check" || fail "r: self-review Comments check"
grep -q 'crosses a module/team boundary' "$UNI" && grep -q 'Comment language follows the surrounding code' "$UNI" \
  && grep -q 'thread-safety' "$UNI" && grep -q 'non-public members whose name already says it' "$UNI" \
  && grep -q 'Code style (self-documenting)' "$UNI" && ! grep -q '^## Code style' "$UNI" \
  && pass "s: _universal.md mirrors n/o/p and points at the pack ## Code style — carrying NO such section itself" || fail "s: _universal mirror"
grep -q '`@param`/`@return`/`@throws` tags that restate the signature' "$QL" && grep -q 'a doc block on a non-public member' "$QL" \
  && grep -q 'A \*missing\* comment or docblock is NOT a finding' "$QL" \
  && pass "u: quality lens comment-what shapes include tag echo + non-public doc block; missing docs still never a finding" || fail "u: quality lens shapes"
echo; [ $rc -eq 0 ] && echo "ALL PASS" || echo "FAILURES PRESENT"; exit $rc
